define({
	MARK_AS_READ: 'Marquer comme (Non lu)Lu',
	DELETE: 'Supprimer',
	UPDATE: 'Mettre à jour',
	PRINT: 'Imprimer',
	SEARCH: 'Rechercher…',
	SEARCH_TIP: 'Recherche dans les articles. Utilisez le préfixe \':\' pour chercher aussi dans le contenu des articles.',
	NEVER: 'Jamais',
	EVERY_5_MINUTES: 'Toutes les 5 minutes',
	EVERY_15_MINUTES: 'Toutes les 15 minutes',
	EVERY_30_MINUTES: 'Toutes les 30 minutes',
	EVERY_HOUR: 'Toutes les heures',
	EVERY_2_HOURS: 'Toutes les 2 heures',
	EVERY_3_HOURS: 'Toutes les 3 heures',
	EVERY_5_HOURS: 'Toutes les 5 heures',
	EVERY_10_HOURS: 'Toutes les 10 heures',
	EVERY_24_HOURS: 'Toutes les 24 heures',
	EVERY_WEEK: 'Toutes les semaines',
	USERNAME: 'Utilisateur',
	PASSWORD: 'Mot de passe',
	CANCEL: 'Annuler',
	OK: 'OK',
	LAYOUT: 'Disposition',
	LINES: 'Liste d’articles',
	SORT_ORDER: 'Ordre de tri',
	DESCENDING: 'Les plus récents en haut',
	ASCENDING: 'Les plus anciens en haut',
	ONE_LINE: 'sur une ligne',
	TWO_LINES: 'sur deux lignes',
	AUTO: 'Automatique',
	FULL_ARTICLE: 'COnsulter l’article complet',
	REALLY_DELETE: 'Souhaitez-vous vraiment supprimer ce flux ?',
	ALL_FEEDS: 'Tous les flux',
	PINNED: 'Épinglés',
	TRASH: 'Poubelle',
	MARK_ALL_AS_READ: 'Tout marquer comme lu',
	PROPERTIES: 'Propriétés',
	UNDELETE: 'Annuler la suppression',
	NEXT_UNREAD: 'Prochain non lu',
	PREV_UNREAD: 'Non lu précédent',
	MARK_AND_NEXT_UNREAD: 'Marquer et prochain non lu',
	MARK_AND_PREV_UNREAD: 'Marquer et non lu précédent',
	PIN: '(Détacher)Épingler',
	PIN_QUESTION_A: 'L’élément « ',
	PIN_QUESTION_B: ' » est épinglé. Souhaitez-vous vraiment le supprimer ?',
	MARK_ALL_QUESTION: 'Souhaitez-vous vraiment marquer tous les articles comme étant lus ?',
	ADD_RSS_SOURCE: 'Ajouter un flux RSS',
	UPDATE_ALL: 'Tout mettre à jour',
	FETCH_TITLE_TIP: 'Si le champ est vide, le titre du flux sera utilisé à la place.',
	NAME: 'Nom',
	ADDRESS: 'Adresse',
	JANUARY: 'Janvier',
	FEBRUARY: 'Février',
	MARCH: 'Mars',
	APRIL: 'Avril',
	MAY: 'Mai',
	JUNE: 'Juin',
	JULY: 'Juillet',
	AUGUST: 'Août',
	SEPTEMBER: 'Septembre',
	OCTOBER: 'Octobre',
	NOVEMBER: 'Novembre',
	DECEMBER: 'Décembre',
	MONDAY: 'Lundi',
	TUESDAY: 'Mardi',
	WEDNESDAY: 'Mercredi',
	THURSDAY: 'Jeudi',
	FRIDAY: 'Vendredi',
	SATURDAY: 'Samedi',
	SUNDAY: 'Dimanche',
	TODAY: 'Aujourd’hui',
	YESTERDAY: 'Hier',
	LAST_WEEK: 'La semaine dernière',
	EARLIER_THIS_MONTH: 'Le mois dernier',
	MORE: 'Plus',
	SETTINGS: 'Réglages',
	EMPTY_TRASH: 'Vider la poubelle',
	RSS_FEED_URL: 'URL du flux : ',
	OPTIONS: 'Options',
	UPDATING_FEEDS: 'Mise à jour des flux',
	UNREAD: 'non lus',
	TOTAL: 'total',
	NEW_FOLDER: 'Nouveau dossier',
	DOWNLOAD: 'Télécharger',
	DELETE_ALL_ARTICLES: 'Supprimer tous les articles',
	DELETE_ALL_Q: 'Souhaitez-vous vraiment supprimer tous les articles ?',
	REALLY_EMPTY_TRASH: 'Souhaitez-vous supprimer définitivement tous les articles présents dans la poubelle ?',
	RENAME: 'Renommer',
	FOLDER_NAME: 'Nom du dossier',

	AUTOREMOVE: 'Autoremove',
	OLDER_THAN_DAY: 'Plus d\'un jour',
	OLDER_THAN_WEEK: 'Plus d\'une semaine',
	OLDER_THAN_MONTH: 'Plus de un mois',
	OLDER_THAN_TWO_MONTHS: 'Plus de deux mois'
});