define({
	MARK_AS_READ: 'Označi kao (ne)pročitano',
	DELETE: 'Obriši',
	UPDATE: 'Ažuriraj',
	PRINT: 'Isprintaj',
	SEARCH: 'Pretraži za...',
	SEARCH_TIP: 'Pretraži članke. Koristi \':\' za pretragu u sadržaju.',
	NEVER: 'Nikada',
	EVERY_5_MINUTES: 'Svakih 5 minuta',
	EVERY_15_MINUTES: 'Svakih 15 minuta',
	EVERY_30_MINUTES: 'Svakih 30 minuta',
	EVERY_HOUR: 'Svaki sat',
	EVERY_2_HOURS: 'Svaka 2 sata',
	EVERY_3_HOURS: 'Svaka 3 sata',
	EVERY_5_HOURS: 'Svakih 5 sati',
	EVERY_10_HOURS: 'Svakih 10 sati',
	EVERY_24_HOURS: 'Svaka 24 sata',
	EVERY_WEEK: 'Svaki tjedan',
	USERNAME: 'Korisničko ime',
	PASSWORD: 'Lozinka',
	CANCEL: 'Poništi',
	OK: 'OK',
	LAYOUT: 'Raspored',
	LINES: 'Linije',
	SORT_ORDER: 'Sortiranje',
	DESCENDING: 'Silazno',
	ASCENDING: 'Uzlazno',
	ONE_LINE: 'Jedno-linijski',
	TWO_LINES: 'Dvo-linijski',
	AUTO: 'Auto',
	FULL_ARTICLE: 'Cijeli članak',
	REALLY_DELETE: 'Dali stvarno želite obrisati ovaj feed?',
	ALL_FEEDS: 'Svi feedovi',
	PINNED: 'Zakačeno',
	TRASH: 'Koš',
	MARK_ALL_AS_READ: 'Označi sve kao pročitano',
	PROPERTIES: 'Svojstva',
	UNDELETE: 'Povrat',
	NEXT_UNREAD: 'Sljedeće nepročitano',
	PREV_UNREAD: 'Predhodno nepročitano',
	MARK_AND_NEXT_UNREAD: 'Označi i idi na sljedeći	nepročitan',
	MARK_AND_PREV_UNREAD: 'Označi i idi na prethodni nepročitan',
	PIN: 'Zakači/Otkači',
	PIN_QUESTION_A: 'Stavka "',
	PIN_QUESTION_B: '" je zakačena. Dali je stvarno želite obrisati?',
	MARK_ALL_QUESTION: 'Dali stvaro želite označiti SVE članke kao pročitane?',
	ADD_RSS_SOURCE: 'Dodaj RSS izvor',
	UPDATE_ALL: 'Ažuriraj sve',
	FETCH_TITLE_TIP: 'U slučaju praznog polja, koristit će se naziv feeda.',
	NAME: 'Naziv',
	ADDRESS: 'Adresa',
	JANUARY: 'Siječanj',
	FEBRUARY: 'Veljača',
	MARCH: 'Ožujak',
	APRIL: 'Travanj',
	MAY: 'Svibanj',
	JUNE: 'Lipanj',
	JULY: 'Srpanj',
	AUGUST: 'Kolovoz',
	SEPTEMBER: 'Rujan',
	OCTOBER: 'Listopad',
	NOVEMBER: 'Studeni',
	DECEMBER: 'Prosinac',
	MONDAY: 'Ponedjeljak',
	TUESDAY: 'Utorak',
	WEDNESDAY: 'Srijeda',
	THURSDAY: 'Četvrtak',
	FRIDAY: 'Petak',
	SATURDAY: 'Subota',
	SUNDAY: 'Nedjelja',
	TODAY: 'Danas',
	YESTERDAY: 'Jučer',
	LAST_WEEK: 'Prošli tjedan',
	EARLIER_THIS_MONTH: 'Ranije ovoga mjeseca',
	MORE: 'Više',
	SETTINGS: 'Postavke',
	EMPTY_TRASH: 'Isprazni koš',
	RSS_FEED_URL: 'RSS feed URL: ',
	OPTIONS: 'Opcije',
	UPDATING_FEEDS: 'Ažuriram feedove',

	UNREAD: 'Nepročitano',
	TOTAL: 'Ukupno',
	NEW_FOLDER: 'Nova mapa',
	DOWNLOAD: 'Preuzmi',
	DELETE_ALL_ARTICLES: 'Obriši sve članke',
	DELETE_ALL_Q: 'Dali stvarno želite potpuno obrisati SVE	članke?',
	REALLY_EMPTY_TRASH: 'Dali stvarno želite potpuno obrisati sve članke iz koša?',
	RENAME: 'Preimenuj',
	FOLDER_NAME: 'Ime mape',

	AUTOREMOVE: 'Automatsko brisanje',
	OLDER_THAN_DAY: 'Starije od dan',
	OLDER_THAN_WEEK: 'Starije od tjedan dana',
	OLDER_THAN_MONTH: 'Starije od mjesec dana',
	OLDER_THAN_TWO_MONTHS: 'Starije od dva mjeseca',
	
	SORT_BY: 'Sortiraj po',
	DATE: 'Datumu',
	TITLE: 'Nazivu',
	AUTHOR: 'Autoru',

	EMAIL: 'E-Mail',
	OPTIONAL: 'neobavezno',
	SUBMIT: 'Pošalji',
	INCLUDE_FEED_LIST: 'Uvrsti listu feedova',
	REPORT: 'Molim opišite problem na engleskom jeziku, ako je moguće.'	
});