define({
	MARK_AS_READ: 'Markeren als (on)gelezen',
	DELETE: 'Verwijderen',
	UPDATE: 'Bijwerken',
	PRINT: 'Afdrukken',
	SEARCH: 'Zoeken naar...',
	SEARCH_TIP: 'Artikelen doorzoeken. Gebruik \':\' om ook de inhoud te doorzoeken.',
	NEVER: 'Nooit',
	EVERY_5_MINUTES: 'Elke 5 minuten',
	EVERY_15_MINUTES: 'Elke 15 minuten',
	EVERY_30_MINUTES: 'Elke 30 minuten',
	EVERY_HOUR: 'Elk uur',
	EVERY_2_HOURS: 'Elke 2 uur',
	EVERY_3_HOURS: 'Elke 3 uur',
	EVERY_5_HOURS: 'Elke 5 uur',
	EVERY_10_HOURS: 'Elke 10 uur',
	EVERY_24_HOURS: 'Elke 24 uur',
	EVERY_WEEK: 'Elke week',
	USERNAME: 'Gebruikersnaam',
	PASSWORD: 'Wachtwoord',
	CANCEL: 'Annuleren',
	OK: 'OK',
	LAYOUT: 'Indeling',
	LINES: 'Regels',
	SORT_ORDER: 'Sorteervolgorder',
	DESCENDING: 'Aflopend',
	ASCENDING: 'Oplopend',
	ONE_LINE: 'Een regel',
	TWO_LINES: 'Twee regels',
	AUTO: 'Automatisch',
	FULL_ARTICLE: 'Volledig artikel',
	REALLY_DELETE: 'Wil je echt deze feed verwijderen?',
	ALL_FEEDS: 'Alle feeds',
	PINNED: 'Gepind',
	TRASH: 'Prullenbak',
	MARK_ALL_AS_READ: 'Alles markeren als gelezen',
	PROPERTIES: 'Eigenschappen',
	UNDELETE: 'Terugzetten',
	NEXT_UNREAD: 'Volgende ongelezen',
	PREV_UNREAD: 'Vorige ongelezen',
	MARK_AND_NEXT_UNREAD: 'Markeren en volgende ongelezen',
	MARK_AND_PREV_UNREAD: 'Markeren en vorige ongelezen',
	PIN: '(Ont)Pinnen',
	PIN_QUESTION_A: 'Item "',
	PIN_QUESTION_B: '" is gepind. Wil je dit echt verwijderen?',
	MARK_ALL_QUESTION: 'Wil je echt ALLE artikelen als gelezen markeren?',
	ADD_RSS_SOURCE: 'RSS-bron toevoegen',
	UPDATE_ALL: 'Alles bijwerken',
	FETCH_TITLE_TIP: 'Als dit veld leeg is, zal in plaats daarvan de titel van de feed worden gebruikt.',
	NAME: 'Naam',
	ADDRESS: 'Adres',
	JANUARY: 'Januari',
	FEBRUARY: 'Februari',
	MARCH: 'Maart',
	APRIL: 'April',
	MAY: 'May',
	JUNE: 'June',
	JULY: 'July',
	AUGUST: 'August',
	SEPTEMBER: 'September',
	OCTOBER: 'Oktober',
	NOVEMBER: 'November',
	DECEMBER: 'December',
	MONDAY: 'Maandag',
	TUESDAY: 'Dinsdag',
	WEDNESDAY: 'Woensdag',
	THURSDAY: 'Donderdag',
	FRIDAY: 'Vrijdag',
	SATURDAY: 'Zaterdag',
	SUNDAY: 'Zondag',
	TODAY: 'Vandaag',
	YESTERDAY: 'Gisteren',
	LAST_WEEK: 'Vorige week',
	EARLIER_THIS_MONTH: 'Eerder deze maand',
	MORE: 'Meer',
	SETTINGS: 'Instellingen',
	EMPTY_TRASH: 'Prullenbak legen',
	RSS_FEED_URL: 'RSS-feedadres: ',
	OPTIONS: 'Opties',
	UPDATING_FEEDS: 'Feeds bijwerken',

	UNREAD: 'ongelezen',
	TOTAL: 'totaal',
	NEW_FOLDER: 'Nieuwe map',
	DOWNLOAD: 'Download',
	DELETE_ALL_ARTICLES: 'Alle artikelen verwijderen',
	DELETE_ALL_Q: 'Wil je echt ALLE artikelen compleet verwijderen?',
	REALLY_EMPTY_TRASH: 'Wil je echt ALLE artikelen compleet verwijderen uit de prullenbak?',
	RENAME: 'Hernoemen',
	FOLDER_NAME: 'Naam van map'
});