define({
	MARK_AS_READ: 'Marcar como (năo) lida',
	DELETE: 'Deletar',
	UPDATE: 'Atualizar',
	PRINT: 'Imprimir',
	SEARCH: 'Procurar por...',
	SEARCH_TIP: 'Procure artigos. Use \':\' para procurar no conteúdo também.',
	NEVER: 'Nunca',
	EVERY_5_MINUTES: 'A Cada 5 minutos',
	EVERY_15_MINUTES: 'A Cada 15 minutos',
	EVERY_30_MINUTES: 'A Cada 30 minutos',
	EVERY_HOUR: 'Cada hora',
	EVERY_2_HOURS: 'A Cada 1 hora',
	EVERY_3_HOURS: 'A Cada 3 horaS',
	EVERY_5_HOURS: 'A Cada 5 horaS',
	EVERY_10_HOURS: 'A Cada 10 horas',
	EVERY_24_HOURS: 'A Cada 24 horas',
	EVERY_WEEK: 'Semanalmente',
	USERNAME: 'Usuário',
	PASSWORD: 'Senha',
	CANCEL: 'Cancelar',
	OK: 'OK',
	LAYOUT: 'Layout',
	LINES: 'Colunas',
	SORT_ORDER: 'Ordenar',
	DESCENDING: 'Decrescente',
	ASCENDING: 'Crescente',
	ONE_LINE: 'Uma Coluna',
	TWO_LINES: 'Duas Colunas',
	AUTO: 'Automático',
	FULL_ARTICLE: 'Artigo Completo',
	REALLY_DELETE: 'Quer realmente deletar esse feed?',
	ALL_FEEDS: 'Todos os feeds',
	PINNED: 'Fixado',
	TRASH: 'Lixeira',
	MARK_ALL_AS_READ: 'Marcar todos como Lido',
	PROPERTIES: 'Propiedades',
	UNDELETE: 'Desfazer deletar',
	NEXT_UNREAD: 'Próximo Năo-Lido',
	PREV_UNREAD: 'Anterior Năo-Lido',
	MARK_AND_NEXT_UNREAD: 'Marcar e ir para o róximo Năo-Lido',
	MARK_AND_PREV_UNREAD: 'Marcar e ir para o anterior Năo-Lido',
	PIN: '(Des)fixar)',
	PIN_QUESTION_A: 'Item "',
	PIN_QUESTION_B: '" está fixado. Quer realmente deletá-lo?',
	MARK_ALL_QUESTION: ' Quer realmente marcar todos os artigos como lido?',
	ADD_RSS_SOURCE: 'Adicionar origem do RSS',
	UPDATE_ALL: 'Atualizar todos',
	FETCH_TITLE_TIP: 'Se esse campo estiver vazio, o título do feed será usado no lugar.',
	NAME: 'Nome',
	ADDRESS: 'Endereço',
	JANUARY: 'Janeiro',
	FEBRUARY: 'Fevereiro',
	MARCH: 'Março',
	APRIL: 'Abril',
	MAY: 'Maio',
	JUNE: 'Junho',
	JULY: 'Julho',
	AUGUST: 'Agosto',
	SEPTEMBER: 'Setembro',
	OCTOBER: 'Outubro',
	NOVEMBER: 'Novembro',
	DECEMBER: 'Dezembro',
	MONDAY: 'Segunda',
	TUESDAY: 'Terça',
	WEDNESDAY: 'Quarta',
	THURSDAY: 'Quinta',
	FRIDAY: 'Sexta',
	SATURDAY: 'Sábado',
	SUNDAY: 'Domingo',
	TODAY: 'Hoje',
	YESTERDAY: 'Ontem',
	LAST_WEEK: 'Semana Passada',
	EARLIER_THIS_MONTH: 'Męs Passado',
	MORE: 'Mais',
	SETTINGS: 'Configuraçőes',
	EMPTY_TRASH: 'Lixeira Vazia',
	RSS_FEED_URL: 'URL do RSS Feed: ',
	OPTIONS: 'Opçőes',
	UPDATING_FEEDS: 'Atualizando feeds',

	UNREAD: 'năo lidas',
	TOTAL: 'total',
	NEW_FOLDER: 'Nova Pasta',
	DOWNLOAD: 'Download',
	DELETE_ALL_ARTICLES: 'Deletar todos os Artigos',
	DELETE_ALL_Q: 'quer realmente deletar todos os artigos?',
	REALLY_EMPTY_TRASH: 'Quer realmente deletar todos os artigos da lixeira?',
	RENAME: 'Renomear',
	FOLDER_NAME: 'Nome da Pasta',

	AUTOREMOVE: 'Autoremove',
	OLDER_THAN_DAY: 'Mais do que um dia',
	OLDER_THAN_WEEK: 'Mais velho de uma semana',
	OLDER_THAN_MONTH: 'Mais velho do que um mês',
	OLDER_THAN_TWO_MONTHS: 'Maior de dois meses'
});