define({
	MARK_AS_READ: 'Означи као (не)прочитано',
	DELETE: 'Избриши',
	UPDATE: 'Ажурирај',
	PRINT: 'Одштампај',
	SEARCH: 'Претрага...',
	SEARCH_TIP: 'Претражи чланке. Користи \':\' за претрагу у садржају.',
	NEVER: 'Никада',
	EVERY_5_MINUTES: 'Сваких 5 минута',
	EVERY_15_MINUTES: 'Сваких 15 минута',
	EVERY_30_MINUTES: 'Сваких 30 минута',
	EVERY_HOUR: 'Сваког сата',
	EVERY_2_HOURS: 'Свака 2 сата',
	EVERY_3_HOURS: 'Свака 3 сата',
	EVERY_5_HOURS: 'Сваких 5 сати',
	EVERY_10_HOURS: 'Сваких 10 сати',
	EVERY_24_HOURS: 'Свака 24 сата',
	EVERY_WEEK: 'Сваке седмице',
	USERNAME: 'Корисничко име',
	PASSWORD: 'Лозинка',
	CANCEL: 'Откажи',
	OK: 'ОК',
	LAYOUT: 'Распоред',
	LINES: 'Линије',
	SORT_ORDER: 'Сортирање',
	DESCENDING: 'Падајуће',
	ASCENDING: 'Растуће',
	ONE_LINE: 'Једна линија',
	TWO_LINES: 'Две линије',
	AUTO: 'Аутоматски',
	FULL_ARTICLE: 'Цели чланак',
	REALLY_DELETE: 'Да ли заиста желите да избришете овај извор?',
	ALL_FEEDS: 'Сви канали',
	PINNED: 'Закачено',
	TRASH: 'Отпад',
	MARK_ALL_AS_READ: 'Означи све као прочитано',
	PROPERTIES: 'Својства',
	UNDELETE: 'Врати',
	NEXT_UNREAD: 'Следеће непрочитано',
	PREV_UNREAD: 'Претходно непрочитано',
	MARK_AND_NEXT_UNREAD: 'Означи и иди на следеће непрочитано',
	MARK_AND_PREV_UNREAD: 'Означи и иди на претходно непрочитано',
	PIN: 'Закачи/Откачи',
	PIN_QUESTION_A: 'Ставка "',
	PIN_QUESTION_B: '" је закачена. Да ли заиста желите да је избришете?',
	MARK_ALL_QUESTION: 'Да ли заиста желите да означите СВЕ чланке као прочитане?',
	ADD_RSS_SOURCE: 'Додај RSS Извор',
	UPDATE_ALL: 'Ажурирај све',
	FETCH_TITLE_TIP: 'Ако је ово поље празно, користиће се назив канала.',
	NAME: 'Име',
	ADDRESS: 'Адреса',
	JANUARY: 'Јануар',
	FEBRUARY: 'Фебруар',
	MARCH: 'Март',
	APRIL: 'Април',
	MAY: 'Мај',
	JUNE: 'Јун',
	JULY: 'Јул',
	AUGUST: 'Август',
	SEPTEMBER: 'Септембар',
	OCTOBER: 'Октобар',
	NOVEMBER: 'Новембар',
	DECEMBER: 'Децембар',
	MONDAY: 'Понедељак',
	TUESDAY: 'Уторак',
	WEDNESDAY: 'Среда',
	THURSDAY: 'Четвртак',
	FRIDAY: 'Петак',
	SATURDAY: 'Субота',
	SUNDAY: 'Недеља',
	TODAY: 'Данас',
	YESTERDAY: 'Јуче',
	LAST_WEEK: 'Прошле седмице',
	EARLIER_THIS_MONTH: 'Раније овог месеца',
	MORE: 'Више',
	SETTINGS: 'Подешавања',
	EMPTY_TRASH: 'Ипразни отпад',
	RSS_FEED_URL: 'Адреса RSS извора: ',
	OPTIONS: 'Опције',
	UPDATING_FEEDS: 'Ажурирање вести',

	UNREAD: 'непрочитано',
	TOTAL: 'укупно',
	NEW_FOLDER: 'Нова фасцикла',
	DOWNLOAD: 'Преузми',
	DELETE_ALL_ARTICLES: 'Избриши све чланке',
	DELETE_ALL_Q: 'Да ли заиста желите да потпуно избришете СВЕ чланке?',
	REALLY_EMPTY_TRASH: 'Да ли заиста желите да потпуно избришете СВЕ чланке из отпада?',
	RENAME: 'Преименуј',
	FOLDER_NAME: 'Име фасцикле',

	AUTOREMOVE: 'Аутоматско брисање',
	OLDER_THAN_DAY: 'Старије од једног дана',
	OLDER_THAN_WEEK: 'Старије од једне седмице',
	OLDER_THAN_MONTH: 'Старије од једног месеца',
	OLDER_THAN_TWO_MONTHS: 'Старије од два месеца',

	SORT_BY: 'Сортирај по',
	DATE: 'Датуму',
	TITLE: 'Називу',
	AUTHOR: 'Аутору',

	EMAIL: 'Адреса е-поште',
	OPTIONAL: 'необавезно',
	SUBMIT: 'Пошаљи',
	INCLUDE_FEED_LIST: 'Укључи листу вести',
	REPORT: 'Опишите проблем, на енглеском ако је могуће.',

	SORTING: 'Сортирање',
	SECONDARY_SORTING: 'Споредно сортирање'
});
