define({
	MARK_AS_READ: 'Okunmadı Olarak İşaretle',
	DELETE: 'Sil',
	UPDATE: 'Güncelle',
	PRINT: 'Yazdır',
	SEARCH: 'İçerik ara...',
	SEARCH_TIP: 'Makaleleri arayabilirsiniz. Eğer makale içeriğinde arama yapmak istiyorsanız \':\' karakterini kullanabilirsiniz.',
	NEVER: 'Hiç',
	EVERY_5_MINUTES: 'Her 5 dakikada',
	EVERY_15_MINUTES: 'Her 15 dakikada',
	EVERY_30_MINUTES: 'Her 30 dakikada',
	EVERY_HOUR: 'Saatte bir',
	EVERY_2_HOURS: 'Her 2 saatte',
	EVERY_3_HOURS: 'Her 3 saatte',
	EVERY_5_HOURS: 'Her 5 saatte',
	EVERY_10_HOURS: 'Her 10 saatte',
	EVERY_24_HOURS: 'Her 24 saatte',
	EVERY_WEEK: 'Haftada bir',
	USERNAME: 'Kullanıcı adı',
	PASSWORD: 'Şifre',
	CANCEL: 'İptal',
	OK: 'Tamam',
	LAYOUT: 'Görünüm',
	LINES: 'Satırlar',
	SORT_ORDER: 'Sıralama Düzeni',
	DESCENDING: 'Azalan',
	ASCENDING: 'Artan',
	ONE_LINE: 'Tek satır',
	TWO_LINES: 'İki satır',
	AUTO: 'Otomatik',
	FULL_ARTICLE: 'Tüm makale',
	REALLY_DELETE: 'Bu beslemeyi gerçekten silmek istiyor musunuz?',
	ALL_FEEDS: 'Tüm Beslemeler',
	PINNED: 'Sabitlenmiş',
	TRASH: 'Çöp Kutusu',
	MARK_ALL_AS_READ: 'Tümünü Okundu Olarak İşaretle',
	PROPERTIES: 'Özellikler',
	UNDELETE: 'Geri al',
	NEXT_UNREAD: 'Sonraki Okunmamış',
	PREV_UNREAD: 'Önceki Okunmamış',
	MARK_AND_NEXT_UNREAD: 'İşaretle ve sonrakine git',
	MARK_AND_PREV_UNREAD: 'İşaretle ve öncekine git',
	PIN: 'Sabitle(me)',
	PIN_QUESTION_A: 'Başlık"',
	PIN_QUESTION_B: '" sabitlendi. Gerçekten silmek istiyor musunuz?',
	MARK_ALL_QUESTION: 'Tüm BAŞLIKLARI okundu olarak işaretlemek istiyor musunuz?',
	ADD_RSS_SOURCE: 'RSS Ekle',
	UPDATE_ALL: 'Tümünü Güncelle',
	FETCH_TITLE_TIP: 'Eğer bu alan boş bırakılırsa, otomatik olarak RSS başlığı kullanılacaktır.',
	NAME: 'İsim',
	ADDRESS: 'URL Adresi',
	JANUARY: 'Ocak',
	FEBRUARY: 'Şubat',
	MARCH: 'Mart',
	APRIL: 'Nisan',
	MAY: 'Mayıs',
	JUNE: 'Haziran',
	JULY: 'Temmuz',
	AUGUST: 'Ağustos',
	SEPTEMBER: 'Eylül',
	OCTOBER: 'Ekim',
	NOVEMBER: 'Kasım',
	DECEMBER: 'Aralık',
	MONDAY: 'Pazartesi',
	TUESDAY: 'Salı',
	WEDNESDAY: 'Çarşamba',
	THURSDAY: 'Perşembe',
	FRIDAY: 'Cuma',
	SATURDAY: 'Cumartesi',
	SUNDAY: 'Pazar',
	TODAY: 'Bugün',
	YESTERDAY: 'Dün',
	LAST_WEEK: 'Geçen Hafta',
	EARLIER_THIS_MONTH: 'Bu Ay Başı',
	MORE: 'Daha fazla',
	SETTINGS: 'Ayarlar',
	EMPTY_TRASH: 'Çöp Kutusunu Boşalt',
	RSS_FEED_URL: 'RSS Bildirim Adresi: ',
	OPTIONS: 'Seçenekleri',
	UPDATING_FEEDS: 'Beslemeler güncelleniyor',

	UNREAD: 'okunmamış',
	TOTAL: 'tottoplamal',
	NEW_FOLDER: 'Yeni Klasör',
	DOWNLOAD: 'İndir',
	DELETE_ALL_ARTICLES: 'Tüm Başlıkları Sil',
	DELETE_ALL_Q: 'Gerçekten TÜM başlıkları silmek istiyor musunuz?',
	REALLY_EMPTY_TRASH: 'Çöp kutusundaki TÜM başlıkları gerçekten silmek istiyor musunuz?',
	RENAME: 'Yeniden Adlandır',
	FOLDER_NAME: 'Klasör ismi',

	AUTOREMOVE: 'Otomatik sil',
	OLDER_THAN_DAY: 'Günden daha eaki',
	OLDER_THAN_WEEK: 'Haftadan daha eski',
	OLDER_THAN_MONTH: 'Aydan daha eski',
	OLDER_THAN_TWO_MONTHS: 'Iki aydan daha eski'
});