define({
	MARK_AS_READ: 'Označit jako (Ne)Přečtené',
	DELETE: 'Odstranit',
	UPDATE: 'Načíst',
	PRINT: 'Tisknout',
	SEARCH: 'Hledat...',
	SEARCH_TIP: 'Prohledávejte položky. Použijte znak \':\' k fulltextovému vyhledávání.',
	NEVER: 'Nikdy',
	EVERY_5_MINUTES: 'Každých 5 minut',
	EVERY_15_MINUTES: 'Každých 15 minut',
	EVERY_30_MINUTES: 'Každých 30 minut',
	EVERY_HOUR: 'Každou hodinu',
	EVERY_2_HOURS: 'Každé 2 hodiny',
	EVERY_3_HOURS: 'Každé 3 hodiny',
	EVERY_5_HOURS: 'Každých 5 hodin',
	EVERY_10_HOURS: 'Každých 10 hodin',
	EVERY_24_HOURS: 'Každých 24 hodin',
	EVERY_WEEK: 'Každý týden',
	USERNAME: 'Jméno',
	PASSWORD: 'Heslo',
	CANCEL: 'Zrušit',
	OK: 'OK',
	LAYOUT: 'Rozvržení',
	LINES: 'Počet řádek',
	SORT_ORDER: 'Řazení',
	DESCENDING: 'Sestupně',
	ASCENDING: 'Vzestupně',
	ONE_LINE: 'Jeden řádek',
	TWO_LINES: 'Dva řádky',
	AUTO: 'Automaticky',
	FULL_ARTICLE: 'Celý článek',
	REALLY_DELETE: 'Určitě chcete odstranit tento zdroj?',
	ALL_FEEDS: 'Všechny zdroje',
	PINNED: 'Označené',
	TRASH: 'Koš',
	MARK_ALL_AS_READ: 'Označit Vše Za Přečtené',
	PROPERTIES: 'Vlastnosti',
	UNDELETE: 'Obnovit',
	NEXT_UNREAD: 'Další Nepřečtená',
	PREV_UNREAD: 'Předchozí Nepřečtená',
	MARK_AND_NEXT_UNREAD: 'Přečíst A Další Nepřečtená',
	MARK_AND_PREV_UNREAD: 'Přečíst A Předchozí Nepřečtená',
	PIN: 'O(d)značit',
	PIN_QUESTION_A: 'Položka "',
	PIN_QUESTION_B: '" je označena. Určitě ji chcete odstranit?',
	MARK_ALL_QUESTION: 'Určitě chcete označit VŠECHNY položky jako přečtené?',
	ADD_RSS_SOURCE: 'Přidat RSS zdroj',
	UPDATE_ALL: 'Nahrát vše',
	FETCH_TITLE_TIP: 'Pokud je prázdný, bude nahrán ze zdroje.',
	NAME: 'Titulek',
	ADDRESS: 'Adresa',
	JANUARY: 'Leden',
	FEBRUARY: 'Únor',
	MARCH: 'Březen',
	APRIL: 'Duben',
	MAY: 'Květen',
	JUNE: 'Červen',
	JULY: 'Červenec',
	AUGUST: 'Srpen',
	SEPTEMBER: 'Září',
	OCTOBER: 'Říjen',
	NOVEMBER: 'Listopad',
	DECEMBER: 'Prosinec',
	MONDAY: 'Pondělí',
	TUESDAY: 'Úterý',
	WEDNESDAY: 'Středa',
	THURSDAY: 'Čtvrtek',
	FRIDAY: 'Pátek',
	SATURDAY: 'Sobota',
	SUNDAY: 'Neděle',
	TODAY: 'Dnes',
	YESTERDAY: 'Včera',
	LAST_WEEK: 'Minulý týden',
	EARLIER_THIS_MONTH: 'Dříve v tomto měsíci',
	MORE: 'Více',
	SETTINGS: 'Nastavení',
	EMPTY_TRASH: 'Vysypat Koš',
	RSS_FEED_URL: 'Zadejte adresu RSS zdroje: ',
	OPTIONS: 'Další možnosti',
	UPDATING_FEEDS: 'Aktualizuji zdroje',

	UNREAD: 'nepřečtených',
	TOTAL: 'celkem',
	NEW_FOLDER: 'Nová Složka',
	DOWNLOAD: 'Stánout',
	DELETE_ALL_ARTICLES: 'Odstranit Všechny Články',
	DELETE_ALL_Q: 'Určitě chcete odstranit VŠECHNY články?',
	REALLY_EMPTY_TRASH: 'Určitě chcete vysypat koš?',
	RENAME: 'Přejmenovat',
	FOLDER_NAME: 'Název složky',

	AUTOREMOVE: 'Automatické mazání',
	OLDER_THAN_DAY: 'Starší než den',
	OLDER_THAN_WEEK: 'Starší než týden',
	OLDER_THAN_MONTH: 'Starší než měsíc',
	OLDER_THAN_TWO_MONTHS: 'Starší než dva měsíce',

	SORT_BY: 'Řadit podle',
	DATE: 'Datum',
	TITLE: 'Název',
	AUTHOR: 'Autor',

	SORTING: 'Hlavní řazení',
	SECONDARY_SORTING: 'Vedlejší řazení'
});