define({
    MARK_AS_READ: 'Mark As (Un)Read',
    DELETE: 'Delete',
    UPDATE: 'Update',
    PRINT: 'Print',
    SEARCH: 'Search for...',
    SEARCH_TIP: 'Search articles. Use \':\' to search in content as well.',
    NEVER: 'Never',
    EVERY_5_MINUTES: 'Every 5 minutes',
    EVERY_15_MINUTES: 'Every 15 minutes',
    EVERY_30_MINUTES: 'Every 30 minutes',
    EVERY_HOUR: 'Every hour',
    EVERY_2_HOURS: 'Every 2 hours',
    EVERY_3_HOURS: 'Every 3 hours',
    EVERY_5_HOURS: 'Every 5 hours',
    EVERY_10_HOURS: 'Every 10 hours',
    EVERY_24_HOURS: 'Every 24 hours',
    EVERY_WEEK: 'Every week',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CANCEL: 'Cancel',
    OK: 'OK',
    LAYOUT: 'Layout',
    LINES: 'Lines',
    SORT_ORDER: 'Sort Order',
    DESCENDING: 'Descending',
    ASCENDING: 'Ascending',
    ONE_LINE: 'One-Line',
    TWO_LINES: 'Two-Lines',
    AUTO: 'Auto',
    FULL_ARTICLE: 'Full article',
    FULL_ARTICLE_SINGLE: 'Full article (only when single selected)',
    REALLY_DELETE: 'Do you really want to delete this feed?',
    ALL_FEEDS: 'All feeds',
    PINNED: 'Pinned',
    TRASH: 'Trash',
    MARK_ALL_AS_READ: 'Mark All As Read',
    PROPERTIES: 'Properties',
    REFETCH: 'Refetch',
    OPENHOME: 'Open feed homepage',
    UNDELETE: 'Undelete',
    NEXT_UNREAD: 'Next Unread',
    PREV_UNREAD: 'Previous Unread',
    MARK_AND_NEXT_UNREAD: 'Mark And Next Unread',
    MARK_AND_PREV_UNREAD: 'Mark And Prev Unread',
    PIN: '(Un)Pin',
    PIN_QUESTION_A: 'Item "',
    PIN_QUESTION_B: '" is pinned. Do you really want to delete it?',
    MARK_ALL_QUESTION: 'Do you really want to mark ALL articles as read?',
    ADD_RSS_SOURCE: 'Add RSS Source',
    UPDATE_ALL: 'Update all',
    FETCH_TITLE_TIP: 'If this field is empty, the title of the feed will be used instead.',
    NAME: 'Name',
    ADDRESS: 'Address',
    PARENT: 'Parent folder',
    JANUARY: 'January',
    FEBRUARY: 'February',
    MARCH: 'March',
    APRIL: 'April',
    MAY: 'May',
    JUNE: 'June',
    JULY: 'July',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'October',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    MONDAY: 'Monday',
    TUESDAY: 'Tuesday',
    WEDNESDAY: 'Wednesday',
    THURSDAY: 'Thursday',
    FRIDAY: 'Friday',
    SATURDAY: 'Saturday',
    SUNDAY: 'Sunday',
    TODAY: 'Today',
    YESTERDAY: 'Yesterday',
    LAST_WEEK: 'Last Week',
    EARLIER_THIS_MONTH: 'Earlier This Month',
    MORE: 'More',
    SETTINGS: 'Settings',
    EMPTY_TRASH: 'Empty Trash',
    RSS_FEED_URL: 'RSS Feed URL: ',
    OPTIONS: 'Options',
    UPDATING_FEEDS: 'Updating feeds',

    UNREAD: 'unread',
    TOTAL: 'total',
    NEW_FOLDER: 'New Folder',
    DOWNLOAD: 'Download',
    DELETE_ALL_ARTICLES: 'Delete All Articles',
    DELETE_ALL_Q: 'Do you really want to comletely delete ALL articles?',
    REALLY_EMPTY_TRASH: 'Do you really want to completely delete all articles from trash?',
    RENAME: 'Rename',
    FOLDER_NAME: 'Folder name',

    AUTOREMOVE: 'Automatically remove after',
    OLDER_THAN_DAY: 'Older than day',
    OLDER_THAN_WEEK: 'Older than week',
    OLDER_THAN_MONTH: 'Older than month',
    OLDER_THAN_TWO_MONTHS: 'Older than two months',

    AUTOREMOVE_SETTING: 'Automatically remove',
    USE_GLOBAL_SETTING: 'Use global setting',
    REMOVE_ALL: 'Remove all',
    KEEP_UNVISITED: 'Keep unvisited',
    KEEP_UNREAD: 'Keep unread',

    SORT_BY: 'Sort By',
    DATE: 'Date',
    TITLE: 'Title',
    AUTHOR: 'Author',

    SORTING: 'Sorting',
    SECONDARY_SORTING: 'Secondary sorting',

    HIDE_OVERLAYS: 'Hide overlays',
    TOGGLE_SHOW_ONLY_UNREAD: 'Toggle show only unread',
    STOP_UPDATE: 'Stop updating feeds',
    OPEN_HOME: 'Open feed homepage',
    SCROLL_INTO_VIEW: 'Scroll into view',
    FOCUS_FEEDS: 'Focus feeds',
    SELECT_NEXT_FEED: 'Select next feed',
    SELECT_PREVIOUS_FEED: 'Select previous feed',
    CLOSE_FOLDERS: 'Close folders',
    OPEN_FOLDERS: 'Open folders',
    TOGGLE_FOLDER: 'Toggle folder',
    SHOW_ARTICLES: 'Show articles',
    SHOW_AND_FOCUS_ARTICLES: 'Show and focus articles',
    SELECT_NEXT_ARTICLE: 'Select next article',
    SELECT_PREVIOUS_ARTICLE: 'Select previous article',
    FOCUS_SEARCH: 'Focus search',
    FOCUS_ARTICLES: 'Focus articles',
    SELECT_ALL_ARTICLES: 'Select All',
    PAGE_UP: 'Page up',
    PAGE_DOWN: 'Page down',
    SCROLL_TO_TOP: 'Scroll to top',
    SCROLL_TO_BOTTOM: 'Scroll to bottom',
    FOCUS_CONTENT: 'Focus article content',
    SCROLL_UP: 'Scroll up',
    SCROLL_DOWN: 'Scroll down',

});
