define({
    MARK_AS_READ: 'Marcar como (No) Leído',
    DELETE: 'Eliminar',
    UPDATE: 'Actualizar',
    PRINT: 'Imprimir',
    SEARCH: 'Buscar por...',
    SEARCH_TIP: 'Buscar artículos. Use \':\' para buscar también dentro del contenido.',
    NEVER: 'Nunca',
    EVERY_5_MINUTES: 'Cada 5 minutos',
    EVERY_15_MINUTES: 'Cada 15 minutos',
    EVERY_30_MINUTES: 'Cada 30 minutos',
    EVERY_HOUR: 'Cada hora',
    EVERY_2_HOURS: 'Cada 2 horas',
    EVERY_3_HOURS: 'Cada 3 horas',
    EVERY_5_HOURS: 'Cada 5 horas',
    EVERY_10_HOURS: 'Cada 10 horas',
    EVERY_24_HOURS: 'Cada 24 horas',
    EVERY_WEEK: 'Cada semana',
    USERNAME: 'Nombre de usuario',
    PASSWORD: 'Contraseña',
    CANCEL: 'Cancelar',
    OK: 'OK',
    LAYOUT: 'Diseño',
    LINES: 'Líneas',
    SORT_ORDER: 'Orden',
    DESCENDING: 'Descendiente',
    ASCENDING: 'Ascendente',
    ONE_LINE: 'Una línea',
    TWO_LINES: 'Dos líneas',
    AUTO: 'Auto',
    FULL_ARTICLE: 'Artículo completo',
    REALLY_DELETE: '¿Realmente desea eliminar este canal?',
    ALL_FEEDS: 'Todos los "Feeds"',
    PINNED: 'Clavado',
    TRASH: 'Papelera',
    MARK_ALL_AS_READ: 'Marcar todos como leídos',
    PROPERTIES: 'Propiedades',
    REFETCH: 'Refetch',
    OPENHOME: 'Abrir página principal del canal',
    UNDELETE: 'Restarurar',
    NEXT_UNREAD: 'Siguiente no leído',
    PREV_UNREAD: 'Anterior no leído',
    MARK_AND_NEXT_UNREAD: 'Marcar y siguiente no leído',
    MARK_AND_PREV_UNREAD: 'Marcar y anterior no leído',
    PIN: '(Des) Clavar',
    PIN_QUESTION_A: 'Ítem "',
    PIN_QUESTION_B: '" está clavado. ¿Realmente desea eliminarlo?',
    MARK_ALL_QUESTION: '¿Realmente desea marcar TODOS los artículos como leídos?',
    ADD_RSS_SOURCE: 'Agregar fuente RSS',
    UPDATE_ALL: 'Actualizar todo',
    FETCH_TITLE_TIP: 'Si este campo se deja vacío, se usará el título del canal.',
    NAME: 'Nombre',
    ADDRESS: 'Dirección',
    PARENT: 'Carpeta superior',
    JANUARY: 'Enero',
    FEBRUARY: 'Febrero',
    MARCH: 'Marzo',
    APRIL: 'Abril',
    MAY: 'Mayo',
    JUNE: 'Junio',
    JULY: 'Julio',
    AUGUST: 'Agosto',
    SEPTEMBER: 'Septiembre',
    OCTOBER: 'Octubre',
    NOVEMBER: 'Noviembre',
    DECEMBER: 'Diciembre',
    MONDAY: 'Lúnes',
    TUESDAY: 'Martes',
    WEDNESDAY: 'Miércoles',
    THURSDAY: 'Jueves',
    FRIDAY: 'Viernes',
    SATURDAY: 'Sábado',
    SUNDAY: 'Domingo',
    TODAY: 'Hoy',
    YESTERDAY: 'Ayer',
    LAST_WEEK: 'La semana pasada',
    EARLIER_THIS_MONTH: 'Antes en éste més',
    MORE: 'Más',
    SETTINGS: 'Configuración',
    EMPTY_TRASH: 'Vaciar papelera',
    RSS_FEED_URL: 'URL del canal RSS: ',
    OPTIONS: 'Opciones',
    UPDATING_FEEDS: 'Actualizando "Feeds"',

    UNREAD: 'no leído',
    TOTAL: 'total',
    NEW_FOLDER: 'Nueva carpeta',
    DOWNLOAD: 'Descarga',
    DELETE_ALL_ARTICLES: 'Eliminar todos los artículos',
    DELETE_ALL_Q: '¿Realmente desea eliminar TODOS los artículos?',
    REALLY_EMPTY_TRASH: '¿Realmente desea eliminar todos los artículos de la papelera?',
    RENAME: 'Renombrar',
    FOLDER_NAME: 'Nombre de la carpeta',

    AUTOREMOVE: 'Auto-eliminar artículos luego de',
    OLDER_THAN_DAY: 'Más de un día',
    OLDER_THAN_WEEK: 'Más de una semana',
    OLDER_THAN_MONTH: 'Más de un mes',
    OLDER_THAN_TWO_MONTHS: 'Más de dos meses',

    AUTOREMOVE_SETTING: 'Eliminar automáticamente',
    USE_GLOBAL_SETTING: 'Usar configuración global',
    REMOVE_ALL: 'Eliminar todo',
    KEEP_UNVISITED: 'Mantener como no visitado',
    KEEP_UNREAD: 'Mantener como no leído',

    SORT_BY: 'Ordenar por',
    DATE: 'Fecha',
    TITLE: 'Título',
    AUTHOR: 'Autor',

    SORTING: 'Orden',
    SECONDARY_SORTING: 'Orden seecundario',


});
