define({
	MARK_AS_READ: 'Olvasottnak/olvasatlannak jelölés',
	DELETE: 'Törlés',
	UPDATE: 'Frissítés',
	PRINT: 'Nyomtatás',
	SEARCH: 'Keresés...',
	SEARCH_TIP: 'Keresés a bejegyzésekben. Használd a \':\'-ot, ha a tartalomban is keresni akarsz!',
	NEVER: 'Soha',
	EVERY_5_MINUTES: '5 percenként',
	EVERY_15_MINUTES: '15 percenként',
	EVERY_30_MINUTES: '30 percenként',
	EVERY_HOUR: 'Óránként',
	EVERY_2_HOURS: '2 óránként',
	EVERY_3_HOURS: '3 óránként',
	EVERY_5_HOURS: '5 óránként',
	EVERY_10_HOURS: '10 óránként',
	EVERY_24_HOURS: '24 óránként',
	EVERY_WEEK: 'Hetente',
	USERNAME: 'Felhasználónév',
	PASSWORD: 'Jelszó',
	CANCEL: 'Mégse',
	OK: 'OK',
	LAYOUT: 'Elrendezés',
	LINES: 'Sorok',
	SORT_ORDER: 'Rendezés',
	DESCENDING: 'Csökkenő',
	ASCENDING: 'Növekvő',
	ONE_LINE: 'Egy sorba',
	TWO_LINES: 'Két sorba',
	AUTO: 'Automatikus',
	FULL_ARTICLE: 'Teljes cikk',
	REALLY_DELETE: 'Biztos, hogy törölni akarod ezt a hírcsatornát?',
	ALL_FEEDS: 'Összes hírcsatorna',
	PINNED: 'Rögzített',
	TRASH: 'Kuka',
	MARK_ALL_AS_READ: 'Az összes megjelölése olvasottnak',
	PROPERTIES: 'Tulajdonságok',
	UNDELETE: 'Törlés visszavonása',
	NEXT_UNREAD: 'Ugrás a következő olvasatlanra',
	PREV_UNREAD: 'Ugrás az előző olvasatlanra',
	MARK_AND_NEXT_UNREAD: 'Olvasottnak jelölés, és ugrás a következő olvasatlanra',
	MARK_AND_PREV_UNREAD: 'Olvasottnak jelölés, és ugrás az előző olvasatlanra',
	PIN: 'Rögzítés/feloldás',
	PIN_QUESTION_A: 'A(z) "',
	PIN_QUESTION_B: '" című bejegyzés rögzítve van. Biztos, hogy törölni akarod?',
	MARK_ALL_QUESTION: 'Biztos, hogy az összes bejegyzést olvasottnak akarod jelölni?',
	ADD_RSS_SOURCE: 'Hírcsatorna forrás hozzáadása',
	UPDATE_ALL: 'Az összes frissítése',
	FETCH_TITLE_TIP: 'Ha üresen hagyod, a csatorna címe fog megjelenni.',
	NAME: 'Név',
	ADDRESS: 'Cím',
	JANUARY: 'Január',
	FEBRUARY: 'Február',
	MARCH: 'Március',
	APRIL: 'Április',
	MAY: 'Május',
	JUNE: 'Június',
	JULY: 'Július',
	AUGUST: 'Augusztus',
	SEPTEMBER: 'Szemptember',
	OCTOBER: 'Október',
	NOVEMBER: 'November',
	DECEMBER: 'December',
	MONDAY: 'Hétfő',
	TUESDAY: 'Kedd',
	WEDNESDAY: 'Szerda',
	THURSDAY: 'Csütörtök',
	FRIDAY: 'Péntek',
	SATURDAY: 'Szombat',
	SUNDAY: 'Vasárnap',
	TODAY: 'Ma',
	YESTERDAY: 'Tegnap',
	LAST_WEEK: 'Az előző héten',
	EARLIER_THIS_MONTH: 'Ebben a hónapban',
	MORE: 'Továbbiak',
	SETTINGS: 'Beállítások',
	EMPTY_TRASH: 'Kuka ürítése',
	RSS_FEED_URL: 'Az RSS csatorna URL-je: ',
	OPTIONS: 'További beállítások',
	UPDATING_FEEDS: 'Hírcsatornák frissítése',

	UNREAD: 'olvasatlan',
	TOTAL: 'összesen',
	NEW_FOLDER: 'Új mappa',
	DOWNLOAD: 'Letöltés',
	DELETE_ALL_ARTICLES: 'Az összes bejegyzés törlése',
	DELETE_ALL_Q: 'Biztos, hogy véglegesen törölni akarod az összes bejegyzést?',
	REALLY_EMPTY_TRASH: 'Biztos, hogy véglegesen törölni akarod a kuka teljes tartalmát?',
	RENAME: 'Átnevezés',
	FOLDER_NAME: 'A mappa neve',

	AUTOREMOVE: 'Autoremove',
	OLDER_THAN_DAY: 'Több mint egy nap',
	OLDER_THAN_WEEK: 'Régebbi, mint egy hét',
	OLDER_THAN_MONTH: 'Az idősebb, mint egy hónap',
	OLDER_THAN_TWO_MONTHS: 'Az idősebb, mint két hónap'
});