define({
	MARK_AS_READ: 'Markeren als (on)gelezen',
	DELETE: 'Verwijderen',
	UPDATE: 'Bijwerken',
	PRINT: 'Afdrukken',
	SEARCH: 'Zoeken naar...',
	SEARCH_TIP: 'Zoek naar artikelen. Gebruik \':\' om ook de inhoud te doorzoeken.',
	NEVER: 'Nooit',
	EVERY_5_MINUTES: 'Elke 5 minuten',
	EVERY_15_MINUTES: 'Elke 15 minuten',
	EVERY_30_MINUTES: 'Elke 30 minuten',
	EVERY_HOUR: 'Elk uur',
	EVERY_2_HOURS: 'Elke 2 uur',
	EVERY_3_HOURS: 'Elke 3 uur',
	EVERY_5_HOURS: 'Elke 5 uur',
	EVERY_10_HOURS: 'Elke 10 uur',
	EVERY_24_HOURS: 'Elke 24 uur',
	EVERY_WEEK: 'Elke week',
	USERNAME: 'Gebruikersnaam',
	PASSWORD: 'Wachtwoord',
	CANCEL: 'Annuleren',
	OK: 'Oké',
	LAYOUT: 'Indeling',
	LINES: 'Regels',
	SORT_ORDER: 'Sorteervolgorde',
	DESCENDING: 'Aflopend',
	ASCENDING: 'Oplopend',
	ONE_LINE: 'Eén regel',
	TWO_LINES: 'Twee regels',
	AUTO: 'Automatisch',
	FULL_ARTICLE: 'Volledig artikel',
	REALLY_DELETE: 'Weet je zeker dat je deze feed wilt verwijderen?',
	ALL_FEEDS: 'Alle feeds',
	PINNED: 'Vastgemaakt',
	TRASH: 'Prullenbak',
	MARK_ALL_AS_READ: 'Alles markeren als gelezen',
	PROPERTIES: 'Eigenschappen',
	UNDELETE: 'Terugzetten',
	NEXT_UNREAD: 'Volgende ongelezen',
	PREV_UNREAD: 'Vorige ongelezen',
	MARK_AND_NEXT_UNREAD: 'Markeren, en volgende ongelezen',
	MARK_AND_PREV_UNREAD: 'Markeren, en vorige ongelezen',
	PIN: 'Los-/Vastmaken',
	PIN_QUESTION_A: 'Item "',
	PIN_QUESTION_B: '" is vastgemaakt. Weet je zeker dat je dit wilt verwijderen?',
	MARK_ALL_QUESTION: 'Weet je zeker dat je ALLE artikelen wilt markeren als gelezen?',
	ADD_RSS_SOURCE: 'RSS-bron toevoegen',
	UPDATE_ALL: 'Alles bijwerken',
	FETCH_TITLE_TIP: 'Als dit veld leeg is, zal in plaats daarvan de feedtitel worden gebruikt.',
	NAME: 'Naam',
	ADDRESS: 'Adres',
	JANUARY: 'Januari',
	FEBRUARY: 'Februari',
	MARCH: 'Maart',
	APRIL: 'April',
	MAY: 'Mei',
	JUNE: 'Juni',
	JULY: 'Juli',
	AUGUST: 'Augustus',
	SEPTEMBER: 'September',
	OCTOBER: 'Oktober',
	NOVEMBER: 'November',
	DECEMBER: 'December',
	MONDAY: 'Maandag',
	TUESDAY: 'Dinsdag',
	WEDNESDAY: 'Woensdag',
	THURSDAY: 'Donderdag',
	FRIDAY: 'Vrijdag',
	SATURDAY: 'Zaterdag',
	SUNDAY: 'Zondag',
	TODAY: 'Vandaag',
	YESTERDAY: 'Gisteren',
	LAST_WEEK: 'Vorige week',
	EARLIER_THIS_MONTH: 'Eerder deze maand',
	MORE: 'Meer',
	SETTINGS: 'Instellingen',
	EMPTY_TRASH: 'Prullenbak legen',
	RSS_FEED_URL: 'RSS-feedadres: ',
	OPTIONS: 'Opties',
	UPDATING_FEEDS: 'Bezig met bijwerken...',

	UNREAD: 'ongelezen',
	TOTAL: 'totaal',
	NEW_FOLDER: 'Nieuwe map',
	DOWNLOAD: 'Downloaden',
	DELETE_ALL_ARTICLES: 'Alle artikelen verwijderen',
	DELETE_ALL_Q: 'Weet je zeker dat je ALLE artikelen volledig wilt verwijderen?',
	REALLY_EMPTY_TRASH: 'Weet je zeker dat je ALLE artikelen volledig wilt verwijderen uit de prullenbak?',
	RENAME: 'Naam wijzigen',
	FOLDER_NAME: 'Mapnaam',

	AUTOREMOVE: 'Automatisch verwijderen',
	OLDER_THAN_DAY: 'Ouder dan één dag',
	OLDER_THAN_WEEK: 'Ouder dan één week',
	OLDER_THAN_MONTH: 'Ouder dan één maand',
	OLDER_THAN_TWO_MONTHS: 'Ouder dan twee maanden'
    
    SORT_BY: 'Sorteren op',
	DATE: 'Datum',
	TITLE: 'Titel',
	AUTHOR: 'Auteur',

	SORTING: 'Sortering',
	SECONDARY_SORTING: 'Secundaire sortering'
});
