define({
	MARK_AS_READ: 'Oznacz jako (nie)przeczytane',
	DELETE: 'Usuń',
	UPDATE: 'Aktualizuj',
	PRINT: 'Drukuj',
	SEARCH: 'Wyszukaj...',
	SEARCH_TIP: 'Szukaj wiadomości. Użyj \':\', aby skorzystać z wyszukiwania pełnotekstowego.',
	NEVER: 'Nigdy',
	EVERY_5_MINUTES: 'Co 5 minut',
	EVERY_15_MINUTES: 'Co 15 minut',
	EVERY_30_MINUTES: 'Co 30 minut',
	EVERY_HOUR: 'Co godzinę',
	EVERY_2_HOURS: 'Co 2 godziny',
	EVERY_3_HOURS: 'Co 3 godziny',
	EVERY_5_HOURS: 'Co 5 godzin',
	EVERY_10_HOURS: 'Co 10 godzin',
	EVERY_24_HOURS: 'Co 24 godziny',
	EVERY_WEEK: 'Co tydzień',
	USERNAME: 'Nazwa użytkownika',
	PASSWORD: 'Hasło',
	CANCEL: 'Anuluj',
	OK: 'OK',
	LAYOUT: 'Układ',
	LINES: 'Liczba linii',
	SORT_ORDER: 'Sortowanie',
	DESCENDING: 'Malejąco',
	ASCENDING: 'Rosnąco',
	ONE_LINE: 'Jedna linia',
	TWO_LINES: 'Dwie linie',
	AUTO: 'Automatycznie',
	FULL_ARTICLE: 'Cały artykuł',
	REALLY_DELETE: 'Czy naprawdę chcesz usunąć ten kanał?',
	ALL_FEEDS: 'Wszystkie kanały',
	PINNED: 'Przypięte',
	TRASH: 'Kosz',
	MARK_ALL_AS_READ: 'Oznacz wszystkie jako przeczytane',
	PROPERTIES: 'Właściwości',
	UNDELETE: 'Przywróć',
	NEXT_UNREAD: 'Następna nieprzeczytana',
	PREV_UNREAD: 'Poprzednia nieprzeczytana',
	MARK_AND_NEXT_UNREAD: 'Przeczytaj i następna nieprzeczyt.',
	MARK_AND_PREV_UNREAD: 'Przeczytaj i poprzednia nieprzeczyt.',
	PIN: 'Przypnij/Odepnij',
	PIN_QUESTION_A: 'Wiadomość "',
	PIN_QUESTION_B: '" jest przypięta. Czy na pewno chcesz ją usunąć?',
	MARK_ALL_QUESTION: 'Czy na pewno chcesz oznaczyć WSZYSTKIE wiadomości jako przeczytane?',
	ADD_RSS_SOURCE: 'Dodaj kanał RSS',
	UPDATE_ALL: 'Aktualizuj wszystkie',
	FETCH_TITLE_TIP: 'Jeśli jest pusty, zostanie pobrany.',
	NAME: 'Nazwa',
	ADDRESS: 'Adres',
    PARENT: 'Folder nadrzędny',
	JANUARY: 'Styczeń',
	FEBRUARY: 'Luty',
	MARCH: 'Marzec',
	APRIL: 'Kwiecień',
	MAY: 'Maj',
	JUNE: 'Czerwiec',
	JULY: 'Lipiec',
	AUGUST: 'Sierpień',
	SEPTEMBER: 'Wrzesień',
	OCTOBER: 'Październik',
	NOVEMBER: 'Listopad',
	DECEMBER: 'Grudzień',
	MONDAY: 'Poniedziałek',
	TUESDAY: 'Wtorek',
	WEDNESDAY: 'Środa',
	THURSDAY: 'Czwartek',
	FRIDAY: 'Piątek',
	SATURDAY: 'Sobota',
	SUNDAY: 'Niedziela',
	TODAY: 'Dzisiaj',
	YESTERDAY: 'Wczoraj',
	LAST_WEEK: 'Ostatni tydzień',
	EARLIER_THIS_MONTH: 'Wcześniej w tym miesiącu',
	MORE: 'Więcej',
	SETTINGS: 'Ustawienia',
	EMPTY_TRASH: 'Opróżnij kosz',
	RSS_FEED_URL: 'Adres kanału RSS: ',
	OPTIONS: 'Opcje',
	UPDATING_FEEDS: 'Aktualizacja kanałów',

	UNREAD: 'nieprzeczytane',
	TOTAL: 'łącznie',
	NEW_FOLDER: 'Nowy folder',
	DOWNLOAD: 'Pobierz',
	DELETE_ALL_ARTICLES: 'Usuń wszystkie wiadomości',
	DELETE_ALL_Q: 'Czy na pewno chcesz całkowicie usunąć WSZYSTKIE wiadomości?',
	REALLY_EMPTY_TRASH: 'Czy na pewno chcesz opróżnić kosz?',
	RENAME: 'Zmień nazwę',
	FOLDER_NAME: 'Nazwa folderu',

	AUTOREMOVE: 'Usuwaj automatycznie starsze niż',
	OLDER_THAN_DAY: 'Dzień',
	OLDER_THAN_WEEK: 'Tydzień',
	OLDER_THAN_MONTH: 'Miesiąc',
	OLDER_THAN_TWO_MONTHS: 'Dwa miesiące',

    AUTOREMOVE_SETTING: 'Usuwaj automatycznie',
    USE_GLOBAL_SETTING: 'Użyj globalnego ustawienia',
    REMOVE_ALL: 'Wszystkie',
    KEEP_UNVISITED: 'Zachowaj nieodwiedzone',
    KEEP_UNREAD: 'Zachowaj nieprzeczytane',

});
