define({
	MARK_AS_READ: 'Отметить прочтённой',
	DELETE: 'Удалить',
	UPDATE: 'Обновление',
	PRINT: 'Печать',
	SEARCH: 'Поиск...',
	SEARCH_TIP: 'Поиск новостей. Используйте \':\' чтобы искать в содержимом.',
	NEVER: 'Никогда',
	EVERY_5_MINUTES: 'Каждые 5 минут',
	EVERY_15_MINUTES: 'Каждые 15 минут',
	EVERY_30_MINUTES: 'Каждые 30 минут',
	EVERY_HOUR: 'Каждый час',
	EVERY_2_HOURS: 'Каждые 2 часа',
	EVERY_3_HOURS: 'Каждые 3 часа',
	EVERY_5_HOURS: 'Каждые 5 часов',
	EVERY_10_HOURS: 'Каждые 10 часов',
	EVERY_24_HOURS: 'Каждые 24 часа',
	EVERY_WEEK: 'Каждую неделю',
	USERNAME: 'Логин',
	PASSWORD: 'Пароль',
	CANCEL: 'Отменить',
	OK: 'Применить',
	LAYOUT: 'Внешний вид',
	LINES: 'Строк в названии',
	SORT_ORDER: 'Порядок сортировки',
	DESCENDING: 'По убыванию',
	ASCENDING: 'По возрастанию',
	ONE_LINE: 'Одна',
	TWO_LINES: 'Две',
	AUTO: 'Авто',
	FULL_ARTICLE: 'Полный текст',
	REALLY_DELETE: 'Вы действительно хотите удалить эту рассылку?',
	ALL_FEEDS: 'Все каналы',
	PINNED: 'Закреплённые',
	TRASH: 'Корзина',
	MARK_ALL_AS_READ: 'Отметить всё прочтённым',
	PROPERTIES: 'Свойства',
	UNDELETE: 'Восстановить',
	NEXT_UNREAD: 'Следующая непрочтённая',
	PREV_UNREAD: 'Предыдущая непрочтённая',
	MARK_AND_NEXT_UNREAD: 'Отметить пр. и к следующей',
	MARK_AND_PREV_UNREAD: 'Отметить пр. и к предыдущей',
	PIN: 'Закрепить',
	PIN_QUESTION_A: 'Новость "',
	PIN_QUESTION_B: '" закреплена. Вы действительно хотите её удалить?',
	MARK_ALL_QUESTION: 'Вы действительно хотите отметить все статьи как прочтённые?',
	ADD_RSS_SOURCE: 'Добавить RSS',
	UPDATE_ALL: 'Обновить всё',
	FETCH_TITLE_TIP: 'Если поле пустое, будет использовано название рассылки.',
	NAME: 'Название',
	ADDRESS: 'Адрес',
	JANUARY: 'Январь',
	FEBRUARY: 'Февраль',
	MARCH: 'Март',
	APRIL: 'Апрель',
	MAY: 'Май',
	JUNE: 'Июнь',
	JULY: 'Июль',
	AUGUST: 'Август',
	SEPTEMBER: 'Сентябрь',
	OCTOBER: 'Октябрь',
	NOVEMBER: 'Ноябрь',
	DECEMBER: 'Декабрь',
	MONDAY: 'Понедельник',
	TUESDAY: 'Вторник',
	WEDNESDAY: 'Среда',
	THURSDAY: 'Четверг',
	FRIDAY: 'Пятница',
	SATURDAY: 'Суббота',
	SUNDAY: 'Воскресенье',
	TODAY: 'Сегодня',
	YESTERDAY: 'Вчера',
	LAST_WEEK: 'На прошлой неделе',
	EARLIER_THIS_MONTH: 'В этом месяце',
	MORE: 'Дополнительно',
	SETTINGS: 'Настройки',
	EMPTY_TRASH: 'Очистить корзину',
	RSS_FEED_URL: 'Адрес RSS рассылки:',
	OPTIONS: 'Опции',
	UPDATING_FEEDS: 'Обновление рассылок',

	UNREAD: 'непрочтённое',
	TOTAL: 'всего',
	NEW_FOLDER: 'Новая группа',
	DOWNLOAD: 'Сохранить',
	DELETE_ALL_ARTICLES: 'Удалить все новости',
	DELETE_ALL_Q: 'Вы действительно хотите удалить все новости?',
	REALLY_EMPTY_TRASH: 'Вы действительно хотите удалить содержимое корзины?',
	RENAME: 'Переименовать',
	FOLDER_NAME: 'Имя группи',

	AUTOREMOVE: 'Автоматическая смазка',
	OLDER_THAN_DAY: 'Более в день',
	OLDER_THAN_WEEK: 'Старше недели',
	OLDER_THAN_MONTH: 'Старше месяц',
	OLDER_THAN_TWO_MONTHS: 'Старше два месяца'
});