define({
	MARK_AS_READ: 'Označiť ako (Ne)Prečítané',
	DELETE: 'Odstrániť',
	UPDATE: 'Aktualizovať',
	PRINT: 'Tlačiť',
	SEARCH: 'Vyhľadať...',
	SEARCH_TIP: 'Vyhľadať položky. Použi \':\' pre plné vyhľadávanie.',
	NEVER: 'Nikdy',
	EVERY_5_MINUTES: 'Každých 5 minút',
	EVERY_15_MINUTES: 'Každých 15 minút',
	EVERY_30_MINUTES: 'Každých 30 minút',
	EVERY_HOUR: 'Každú hodinu',
	EVERY_2_HOURS: 'Každé 2 hodiny',
	EVERY_3_HOURS: 'Každé 3 hodiny',
	EVERY_5_HOURS: 'Každých 5 hodín',
	EVERY_10_HOURS: 'Každých 10 hodín',
	EVERY_24_HOURS: 'Každých 24 hodín',
	EVERY_WEEK: 'Každý týždeň',
	USERNAME: 'Meno',
	PASSWORD: 'Heslo',
	CANCEL: 'Zrušiť',
	OK: 'OK',
	LAYOUT: 'Zobrazenie správ',
	LINES: 'Počet riadkov',
	SORT_ORDER: 'Zoradenie',
	DESCENDING: 'Zostupne',
	ASCENDING: 'Vzostupne',
	ONE_LINE: 'Jeden riadok',
	TWO_LINES: 'Dva riadky',
	AUTO: 'Automaticky',
	FULL_ARTICLE: 'Celý článok',
	REALLY_DELETE: 'Skutočne chcete vymazať tento zdroj?',
	ALL_FEEDS: 'Všetky zdroje',
	PINNED: 'Označené',
	TRASH: 'Kôš',
	MARK_ALL_AS_READ: 'Označiť všetko ako prečítané',
	PROPERTIES: 'Nastavenia',
	UNDELETE: 'Obnoviť',
	NEXT_UNREAD: 'Ďalšia neprečítaná',
	PREV_UNREAD: 'Predošlá neprečítaná',
	MARK_AND_NEXT_UNREAD: 'Prečítať a ďalšia neprečítaná',
	MARK_AND_PREV_UNREAD: 'Prečítať a predošlá neprečítaná',
	PIN: 'O(d)značiť',
	PIN_QUESTION_A: 'Položka "',
	PIN_QUESTION_B: '" je označená. Chcete ju zmazať?',
	MARK_ALL_QUESTION: 'Chcete označiť všetky položky, ako prečítané?',
	ADD_RSS_SOURCE: 'Pridať RSS zdroj',
	UPDATE_ALL: 'Aktualizovať všetko',
	FETCH_TITLE_TIP: 'Ak je toto pole prázdne, tak bude použitý názov zo zdroja.',
	NAME: 'Titulok',
	ADDRESS: 'Adresa',
	JANUARY: 'Január',
	FEBRUARY: 'Február',
	MARCH: 'Marec',
	APRIL: 'Apríl',
	MAY: 'Máj',
	JUNE: 'Jún',
	JULY: 'Júl',
	AUGUST: 'August',
	SEPTEMBER: 'September',
	OCTOBER: 'Október',
	NOVEMBER: 'November',
	DECEMBER: 'December',
	MONDAY: 'Pondelok',
	TUESDAY: 'Utorok',
	WEDNESDAY: 'Streda',
	THURSDAY: 'Štvrtok',
	FRIDAY: 'Piatok',
	SATURDAY: 'Sobota',
	SUNDAY: 'Nedeľa',
	TODAY: 'Dnes',
	YESTERDAY: 'Včera',
	LAST_WEEK: 'Minulý týždeň',
	EARLIER_THIS_MONTH: 'Pred mesiacom',
	MORE: 'Viac',
	SETTINGS: 'Nastavenie',
	EMPTY_TRASH: 'Vysypať kôš',
	RSS_FEED_URL: 'Adresa RSS zdroja: ',
	OPTIONS: 'Ďalšie možnosti',
	UPDATING_FEEDS: 'Aktualizácia zdrojov',

	UNREAD: 'neprečítaných', 
	TOTAL: 'celkom', 
	NEW_FOLDER: 'Nová zložka', 
	DOWNLOAD: 'Stiahnúť', 
	DELETE_ALL_ARTICLES: 'Zmazať všetky správy',
	DELETE_ALL_Q: 'Naozaj chcete zmazať VŠETKY správy?',
	REALLY_EMPTY_TRASH: 'Chcete vymazať všetky spávy z koša?',
	RENAME: 'Premenovať',
	FOLDER_NAME: 'Názov zložky',

	AUTOREMOVE: 'Automatické mazanie', 
	OLDER_THAN_DAY: 'Staršie ako deň', 
	OLDER_THAN_WEEK: 'Staršie ako týždeň', 
	OLDER_THAN_MONTH: 'Staršie ako mesiac', 
	OLDER_THAN_TWO_MONTHS: 'Staršie ako dva mesiace'
});