var lang = {
	get c() {
		return this[settings.get('lang')] || this.en;
	},
	en: {
		MARK_AS_READ: 'Mark As (Un)Read',
		DELETE: 'Delete',
		UPDATE: 'Update',
		PRINT: 'Print',
		SEARCH: 'Search for...',
		SEARCH_TIP: 'Search articles. Use \':\' to search in content as well.',
		NEVER: 'Never',
		EVERY_5_MINUTES: 'Every 5 minutes',
		EVERY_15_MINUTES: 'Every 15 minutes',
		EVERY_30_MINUTES: 'Every 30 minutes',
		EVERY_HOUR: 'Every hour',
		EVERY_2_HOURS: 'Every 2 hours',
		EVERY_3_HOURS: 'Every 3 hours',
		EVERY_5_HOURS: 'Every 5 hours',
		EVERY_10_HOURS: 'Every 10 hours',
		EVERY_24_HOURS: 'Every 24 hours',
		EVERY_WEEK: 'Every week',
		USERNAME: 'Username',
		PASSWORD: 'Password',
		CANCEL: 'Cancel',
		OK: 'OK',
		LAYOUT: 'Layout',
		LINES: 'Lines',
		SORT_ORDER: 'Sort Order',
		DESCENDING: 'Descending',
		ASCENDING: 'Ascending',
		ONE_LINE: 'One-Line',
		TWO_LINES: 'Two-Lines',
		AUTO: 'Auto',
		FULL_ARTICLE: 'Full article',
		REALLY_DELETE: 'Do you really want to delete this feed?',
		ALL_FEEDS: 'All feeds',
		PINNED: 'Pinned',
		TRASH: 'Trash',
		MARK_ALL_AS_READ: 'Mark All As Read',
		PROPERTIES: 'Properties',
		UNDELETE: 'Undelete',
		NEXT_UNREAD: 'Next Unread',
		PREV_UNREAD: 'Previous Unread',
		MARK_AND_NEXT_UNREAD: 'Mark And Next Unread',
		MARK_AND_PREV_UNREAD: 'Mark And Prev Unread',
		PIN: '(Un)Pin',
		PIN_QUESTION_A: 'Item "',
		PIN_QUESTION_B: '" is pinned. Do you really want to delete it?',
		MARK_ALL_QUESTION: 'Do you really want to mark ALL articles as read?',
		ADD_RSS_SOURCE: 'Add RSS Source',
		UPDATE_ALL: 'Update all',
		FETCH_TITLE_TIP: 'If this field is empty, the title of the feed will be used instead.',
		NAME: 'Name',
		ADDRESS: 'Address',
		JANUARY: 'January',
		FEBRUARY: 'February',
		MARCH: 'March',
		APRIL: 'April',
		MAY: 'May',
		JUNE: 'June',
		JULY: 'July',
		AUGUST: 'August',
		SEPTEMBER: 'Semptember',
		OCTOBER: 'October',
		NOVEMBER: 'November',
		DECEMBER: 'December',
		MONDAY: 'Monday',
		TUESDAY: 'Tuesday',
		WEDNESDAY: 'Wednesday',
		THURSDAY: 'Thursday',
		FRIDAY: 'Friday',
		SATURDAY: 'Saturday',
		SUNDAY: 'Sunday',
		TODAY: 'Today',
		YESTERDAY: 'Yesterday',
		LAST_WEEK: 'Last Week',
		EARLIER_THIS_MONTH: 'Earlier This Month',
		MORE: 'More',
		SETTINGS: 'Settings',
		EMPTY_TRASH: 'Empty Trash',
		RSS_FEED_URL: 'RSS Feed URL: ',
		OPTIONS: 'Options',
		UPDATING_FEEDS: 'Updating feeds',

		UNREAD: 'unread',
		TOTAL: 'total',
		NEW_FOLDER: 'New Folder',
		DOWNLOAD: 'Download',
		DELETE_ALL_ARTICLES: 'Delete All Articles',
		DELETE_ALL_Q: 'Do you really want to comletelly delete ALL articles?',
		REALLY_EMPTY_TRASH: 'Do you really want to completly delete all articles from trash?',
		RENAME: 'Rename'
	},
	cs: {
		MARK_AS_READ: 'Označit jako (Ne)Přečtené',
		DELETE: 'Odstranit',
		UPDATE: 'Načíst',
		PRINT: 'Tisknout',
		SEARCH: 'Hledat...',
		SEARCH_TIP: 'Prohledávejte položky. Použijte znak \':\' k fulltextovému vyhledávání.',
		NEVER: 'Nikdy',
		EVERY_5_MINUTES: 'Každých 5 minut',
		EVERY_15_MINUTES: 'Každých 15 minut',
		EVERY_30_MINUTES: 'Každých 30 minut',
		EVERY_HOUR: 'Každou hodinu',
		EVERY_2_HOURS: 'Každé 2 hodiny',
		EVERY_3_HOURS: 'Každé 3 hodiny',
		EVERY_5_HOURS: 'Každých 5 hodin',
		EVERY_10_HOURS: 'Každých 10 hodin',
		EVERY_24_HOURS: 'Každých 24 hodin',
		EVERY_WEEK: 'Každý týden',
		USERNAME: 'Jméno',
		PASSWORD: 'Heslo',
		CANCEL: 'Zrušit',
		OK: 'OK',
		LAYOUT: 'Rozvržení',
		LINES: 'Počet řádek',
		SORT_ORDER: 'Řazení',
		DESCENDING: 'Sestupně',
		ASCENDING: 'Vzestupně',
		ONE_LINE: 'Jeden řádek',
		TWO_LINES: 'Dva řádky',
		AUTO: 'Automaticky',
		FULL_ARTICLE: 'Celý článek',
		REALLY_DELETE: 'Určitě chcete odstranit tento zdroj?',
		ALL_FEEDS: 'Všechny zdroje',
		PINNED: 'Označené',
		TRASH: 'Koš',
		MARK_ALL_AS_READ: 'Označit Vše Za Přečtené',
		PROPERTIES: 'Vlastnosti',
		UNDELETE: 'Obnovit',
		NEXT_UNREAD: 'Další Nepřečtená',
		PREV_UNREAD: 'Předchozí Nepřečtená',
		MARK_AND_NEXT_UNREAD: 'Přečíst A Další Nepřečtená',
		MARK_AND_PREV_UNREAD: 'Přečíst A Předchozí Nepřečtená',
		PIN: 'O(d)značit',
		PIN_QUESTION_A: 'Položka "',
		PIN_QUESTION_B: '" je označena. Určitě ji chcete odstranit?',
		MARK_ALL_QUESTION: 'Určitě chcete označit VŠECHNY položky jako přečtené?',
		ADD_RSS_SOURCE: 'Přidat RSS zdroj',
		UPDATE_ALL: 'Nahrát vše',
		FETCH_TITLE_TIP: 'Pokud je prázdný, bude nahrán ze zdroje.',
		NAME: 'Titulek',
		ADDRESS: 'Adresa',
		JANUARY: 'Leden',
		FEBRUARY: 'Únor',
		MARCH: 'Březen',
		APRIL: 'Duben',
		MAY: 'Květen',
		JUNE: 'Červen',
		JULY: 'Červenec',
		AUGUST: 'Srpen',
		SEPTEMBER: 'Září',
		OCTOBER: 'Říjen',
		NOVEMBER: 'Listopad',
		DECEMBER: 'Prosinec',
		MONDAY: 'Pondělí',
		TUESDAY: 'Úterý',
		WEDNESDAY: 'Středa',
		THURSDAY: 'Čtvrtek',
		FRIDAY: 'Pátek',
		SATURDAY: 'Sobota',
		SUNDAY: 'Neděle',
		TODAY: 'Dnes',
		YESTERDAY: 'Včera',
		LAST_WEEK: 'Minulý týden',
		EARLIER_THIS_MONTH: 'Dříve v tomto měsíci',
		MORE: 'Více',
		SETTINGS: 'Nastavení',
		EMPTY_TRASH: 'Vysypat Koš',
		RSS_FEED_URL: 'Zadejte adresu RSS zdroje: ',
		OPTIONS: 'Další možnosti',
		UPDATING_FEEDS: 'Aktualizuji zdroje',

		UNREAD: 'nepřečtených',
		TOTAL: 'celkem',
		NEW_FOLDER: 'Nová Složka',
		DOWNLOAD: 'Stánout',
		DELETE_ALL_ARTICLES: 'Odstranit Všechny Články',
		DELETE_ALL_Q: 'Určitě chcete odstranit VŠECHNY články?',
		REALLY_EMPTY_TRASH: 'Určitě chcete vysypat koš?',
		RENAME: 'Přejmenovat'
	},
	de: {
		MARK_AS_READ: 'Als (un)gelesen markieren',
		DELETE: 'Löschen',
		UPDATE: 'Aktualisieren',
		PRINT: 'Drucken',
		SEARCH: 'Suche nach...',
		SEARCH_TIP: 'Artikel suchen. Benutzen Sie \':\' um auch den Inhalt zu durchsuchen.',
		NEVER: 'Niemals',
		EVERY_5_MINUTES: 'Alle 5 Minuten',
		EVERY_15_MINUTES: 'Alle 15 Minuten',
		EVERY_30_MINUTES: 'Alle 30 Minuten',
		EVERY_HOUR: 'Jede Stunde',
		EVERY_2_HOURS: 'Alle 2 Stunden',
		EVERY_3_HOURS: 'Alle 3 Stunden',
		EVERY_5_HOURS: 'Alle 5 Stunden',
		EVERY_10_HOURS: 'Alle 10 Stunden',
		EVERY_24_HOURS: 'Alle 24 Stunden',
		EVERY_WEEK: 'Jede Woche',
		USERNAME: 'Benutzername',
		PASSWORD: 'Passwort',
		CANCEL: 'Abbrechen',
		OK: 'OK',
		LAYOUT: 'Layout',
		LINES: 'Zeilen',
		SORT_ORDER: 'Sortierung',
		DESCENDING: 'Absteigend',
		ASCENDING: 'Aufsteigend',
		ONE_LINE: 'Einzeilig',
		TWO_LINES: 'Zweizeilig',
		AUTO: 'Automatisch',
		FULL_ARTICLE: 'Vollständiger Artikel',
		REALLY_DELETE: 'Möchten Sie diesen Feed wirklich löschen?',
		ALL_FEEDS: 'Alle Feeds',
		PINNED: 'Angeheftet',
		TRASH: 'Papierkorb',
		MARK_ALL_AS_READ: 'Alle als gelesen markieren',
		PROPERTIES: 'Eigenschaften',
		UNDELETE: 'Wiederherstellen',
		NEXT_UNREAD: 'Nächste Ungelesene',
		PREV_UNREAD: 'Vorherige Ungelesene',
		MARK_AND_NEXT_UNREAD: 'Gelesen, nächste Ungelesene',
		MARK_AND_PREV_UNREAD: 'Gelesen, vorherige Ungelesene',
		PIN: 'Anheften/Lösen',
		PIN_QUESTION_A: 'Der Artikel "',
		PIN_QUESTION_B: '" ist angeheftet. Möchten Sie ihn wirklich löschen?',
		MARK_ALL_QUESTION: 'Möchten sie wirklich ALLE Artikel als gelesen markieren?',
		ADD_RSS_SOURCE: 'Feed hinzufügen ...',
		UPDATE_ALL: 'Alle aktualisieren',
		FETCH_TITLE_TIP: 'Leer für Auto-Titel',
		NAME: 'Titel',
		ADDRESS: 'Addresse',
		JANUARY: 'Januar',
		FEBRUARY: 'Februar',
		MARCH: 'März',
		APRIL: 'April',
		MAY: 'Mai',
		JUNE: 'Juni',
		JULY: 'Juli',
		AUGUST: 'August',
		SEPTEMBER: 'Semptember',
		OCTOBER: 'Oktober',
		NOVEMBER: 'November',
		DECEMBER: 'Dezember',
		MONDAY: 'Montag',
		TUESDAY: 'Dienstag',
		WEDNESDAY: 'Mittwoch',
		THURSDAY: 'Donnerstag',
		FRIDAY: 'Freitag',
		SATURDAY: 'Samstag',
		SUNDAY: 'Sonntag',
		TODAY: 'Heute',
		YESTERDAY: 'Gestern',
		LAST_WEEK: 'Letzte Woche',
		EARLIER_THIS_MONTH: 'Früher in diesem Monat',
		MORE: 'Mehr',
		SETTINGS: 'Einstellungen',
		EMPTY_TRASH: 'Papierkorb leeren',
		RSS_FEED_URL: 'Feed: ',
		OPTIONS: 'Einstellungen',
		UPDATING_FEEDS: 'Feeds aktualisierens',

		UNREAD: 'ungelesen',
		TOTAL: 'gesamt',
		NEW_FOLDER: 'Neuer Ordner',
		DOWNLOAD: 'Download',
		DELETE_ALL_ARTICLES: 'Alle Artikel löschen',
		DELETE_ALL_Q: 'Möchten sie wirklich ALLE Artikel löschen?',
		REALLY_EMPTY_TRASH: 'Möchten sie alle Artikel im Papierkorb endgültig löschen?',
		RENAME: 'Umbenennen'
	},
	pl: {
		MARK_AS_READ: 'Oznacz jako (nie)przeczytane',
		DELETE: 'Usuń',
		UPDATE: 'Aktualizuj',
		PRINT: 'Drukuj',
		SEARCH: 'Wyszukaj...',
		SEARCH_TIP: 'Szukaj wiadomości. Użyj \':\', aby skorzystać z wyszukiwania pełnotekstowego.',
		NEVER: 'Nigdy',
		EVERY_5_MINUTES: 'Co 5 minut',
		EVERY_15_MINUTES: 'Co 15 minut',
		EVERY_30_MINUTES: 'Co 30 minut',
		EVERY_HOUR: 'Co godzinę',
		EVERY_2_HOURS: 'Co 2 godziny',
		EVERY_3_HOURS: 'Co 3 godziny',
		EVERY_5_HOURS: 'Co 5 godzin',
		EVERY_10_HOURS: 'Co 10 godzin',
		EVERY_24_HOURS: 'Co 24 godziny',
		EVERY_WEEK: 'Co tydzień',
		USERNAME: 'Nazwa użytkownika',
		PASSWORD: 'Hasło',
		CANCEL: 'Anuluj',
		OK: 'OK',
		LAYOUT: 'Układ',
		LINES: 'Liczba linii',
		SORT_ORDER: 'Sortowanie',
		DESCENDING: 'Malejąco',
		ASCENDING: 'Rosnąco',
		ONE_LINE: 'Jedna linia',
		TWO_LINES: 'Dwie linie',
		AUTO: 'Automatycznie',
		FULL_ARTICLE: 'Cały artykuł',
		REALLY_DELETE: 'Czy naprawdę chcesz usunąć ten kanał?',
		ALL_FEEDS: 'Wszystkie kanały',
		PINNED: 'Przypięte',
		TRASH: 'Kosz',
		MARK_ALL_AS_READ: 'Oznacz wszystkie jako przeczytane',
		PROPERTIES: 'Właściwości',
		UNDELETE: 'Przywróć',
		NEXT_UNREAD: 'Następna nieprzeczytana',
		PREV_UNREAD: 'Poprzednia nieprzeczytana',
		MARK_AND_NEXT_UNREAD: 'Przeczytaj i następna nieprzeczyt.',
		MARK_AND_PREV_UNREAD: 'Przeczytaj i poprzednia nieprzeczyt.',
		PIN: 'Przypnij/Odepnij',
		PIN_QUESTION_A: 'Wiadomość "',
		PIN_QUESTION_B: '" jest przypięta. Czy na pewno chcesz ją usunąć?',
		MARK_ALL_QUESTION: 'Czy na pewno chcesz oznaczyć WSZYSTKIE wiadomości jako przeczytane?',
		ADD_RSS_SOURCE: 'Dodaj kanał RSS',
		UPDATE_ALL: 'Aktualizuj wszystkie',
		FETCH_TITLE_TIP: 'Jeśli jest pusty, zostanie pobrany.',
		NAME: 'Nazwa',
		ADDRESS: 'Adres',
		JANUARY: 'Styczeń',
		FEBRUARY: 'Luty',
		MARCH: 'Marzec',
		APRIL: 'Kwiecień',
		MAY: 'Maj',
		JUNE: 'Czerwiec',
		JULY: 'Lipiec',
		AUGUST: 'Sierpień',
		SEPTEMBER: 'Wrzesień',
		OCTOBER: 'Październik',
		NOVEMBER: 'Listopad',
		DECEMBER: 'Grudzień',
		MONDAY: 'Poniedziałek',
		TUESDAY: 'Wtorek',
		WEDNESDAY: 'Środa',
		THURSDAY: 'Czwartek',
		FRIDAY: 'Piątek',
		SATURDAY: 'Sobota',
		SUNDAY: 'Niedziela',
		TODAY: 'Dzisiaj',
		YESTERDAY: 'Wczoraj',
		LAST_WEEK: 'Ostatni tydzień',
		EARLIER_THIS_MONTH: 'Wcześniej w tym miesiącu',
		MORE: 'Więcej',
		SETTINGS: 'Ustawienia',
		EMPTY_TRASH: 'Opróżnij kosz',
		RSS_FEED_URL: 'Adres kanału RSS: ',
		OPTIONS: 'Opcje',
		UPDATING_FEEDS: 'Aktualizacja kanałów',

		UNREAD: 'unread',
		TOTAL: 'total',
		NEW_FOLDER: 'New Folder',
		DOWNLOAD: 'Download',
		DELETE_ALL_ARTICLES: 'Delete All Articles',
		DELETE_ALL_Q: 'Do you really want to comletelly delete ALL articles?',
		REALLY_EMPTY_TRASH: 'Do you really want to completly delete all articles from trash?',
		RENAME: 'Rename'
	},
	tr: {
		MARK_AS_READ: 'Okunmadı Olarak İşaretle',
		DELETE: 'Sil',
		UPDATE: 'Güncelle',
		PRINT: 'Yazdır',
		SEARCH: 'İçerik ara...',
		SEARCH_TIP: 'Makaleleri arayabilirsiniz. Eğer makale içeriğinde arama yapmak istiyorsanız \':\' karakterini kullanabilirsiniz.',
		NEVER: 'Hiç',
		EVERY_5_MINUTES: 'Her 5 dakikada',
		EVERY_15_MINUTES: 'Her 15 dakikada',
		EVERY_30_MINUTES: 'Her 30 dakikada',
		EVERY_HOUR: 'Saatte bir',
		EVERY_2_HOURS: 'Her 2 saatte',
		EVERY_3_HOURS: 'Her 3 saatte',
		EVERY_5_HOURS: 'Her 5 saatte',
		EVERY_10_HOURS: 'Her 10 saatte',
		EVERY_24_HOURS: 'Her 24 saatte',
		EVERY_WEEK: 'Haftada bir',
		USERNAME: 'Kullanıcı adı',
		PASSWORD: 'Şifre',
		CANCEL: 'İptal',
		OK: 'Tamam',
		LAYOUT: 'Görünüm',
		LINES: 'Satırlar',
		SORT_ORDER: 'Sıralama Düzeni',
		DESCENDING: 'Azalan',
		ASCENDING: 'Artan',
		ONE_LINE: 'Tek satır',
		TWO_LINES: 'İki satır',
		AUTO: 'Otomatik',
		FULL_ARTICLE: 'Tüm makale',
		REALLY_DELETE: 'Bu beslemeyi gerçekten silmek istiyor musunuz?',
		ALL_FEEDS: 'Tüm Beslemeler',
		PINNED: 'Sabitlenmiş',
		TRASH: 'Çöp Kutusu',
		MARK_ALL_AS_READ: 'Tümünü Okundu Olarak İşaretle',
		PROPERTIES: 'Özellikler',
		UNDELETE: 'Geri al',
		NEXT_UNREAD: 'Sonraki Okunmamış',
		PREV_UNREAD: 'Önceki Okunmamış',
		MARK_AND_NEXT_UNREAD: 'İşaretle ve sonrakine git',
		MARK_AND_PREV_UNREAD: 'İşaretle ve öncekine git',
		PIN: 'Sabitle(me)',
		PIN_QUESTION_A: 'Başlık"',
		PIN_QUESTION_B: '" sabitlendi. Gerçekten silmek istiyor musunuz?',
		MARK_ALL_QUESTION: 'Tüm BAŞLIKLARI okundu olarak işaretlemek istiyor musunuz?',
		ADD_RSS_SOURCE: 'RSS Ekle',
		UPDATE_ALL: 'Tümünü Güncelle',
		FETCH_TITLE_TIP: 'Eğer bu alan boş bırakılırsa, otomatik olarak RSS başlığı kullanılacaktır.',
		NAME: 'İsim',
		ADDRESS: 'URL Adresi',
		JANUARY: 'Ocak',
		FEBRUARY: 'Şubat',
		MARCH: 'Mart',
		APRIL: 'Nisan',
		MAY: 'Mayıs',
		JUNE: 'Haziran',
		JULY: 'Temmuz',
		AUGUST: 'Ağustos',
		SEPTEMBER: 'Eylül',
		OCTOBER: 'Ekim',
		NOVEMBER: 'Kasım',
		DECEMBER: 'Aralık',
		MONDAY: 'Pazartesi',
		TUESDAY: 'Salı',
		WEDNESDAY: 'Çarşamba',
		THURSDAY: 'Perşembe',
		FRIDAY: 'Cuma',
		SATURDAY: 'Cumartesi',
		SUNDAY: 'Pazar',
		TODAY: 'Bugün',
		YESTERDAY: 'Dün',
		LAST_WEEK: 'Geçen Hafta',
		EARLIER_THIS_MONTH: 'Bu Ay Başı',
		MORE: 'Daha fazla',
		SETTINGS: 'Ayarlar',
		EMPTY_TRASH: 'Çöp Kutusunu Boşalt',
		RSS_FEED_URL: 'RSS Bildirim Adresi: ',
		OPTIONS: 'Seçenekleri',
		UPDATING_FEEDS: 'Beslemeler güncelleniyor',

		UNREAD: 'okunmamış',
		TOTAL: 'tottoplamal',
		NEW_FOLDER: 'Yeni Klasör',
		DOWNLOAD: 'İndir',
		DELETE_ALL_ARTICLES: 'Delete All Articles',
		DELETE_ALL_Q: 'Do you really want to comletelly delete ALL articles?',
		REALLY_EMPTY_TRASH: 'Do you really want to completly delete all articles from trash?',
		RENAME: 'Rename'
	},
	sk: {
		MARK_AS_READ: 'Označiť ako (Ne)Prečítané',
		DELETE: 'Odstrániť',
		UPDATE: 'Aktualizovať',
		PRINT: 'Tlačiť',
		SEARCH: 'Vyhľadať...',
		SEARCH_TIP: 'Vyhľadať položky. Použi \':\' pre plné vyhľadávanie.',
		NEVER: 'Nikdy',
		EVERY_5_MINUTES: 'Každých 5 minút',
		EVERY_15_MINUTES: 'Každých 15 minút',
		EVERY_30_MINUTES: 'Každých 30 minút',
		EVERY_HOUR: 'Každú hodinu',
		EVERY_2_HOURS: 'Každé 2 hodiny',
		EVERY_3_HOURS: 'Každé 3 hodiny',
		EVERY_5_HOURS: 'Každých 5 hodín',
		EVERY_10_HOURS: 'Každých 10 hodín',
		EVERY_24_HOURS: 'Každých 24 hodín',
		EVERY_WEEK: 'Každý týždeň',
		USERNAME: 'Meno',
		PASSWORD: 'Heslo',
		CANCEL: 'Zrušiť',
		OK: 'OK',
		LAYOUT: 'Zobrazenie správ',
		LINES: 'Počet riadkov',
		SORT_ORDER: 'Zoradenie',
		DESCENDING: 'Zostupne',
		ASCENDING: 'Vzostupne',
		ONE_LINE: 'Jeden riadok',
		TWO_LINES: 'Dva riadky',
		AUTO: 'Automaticky',
		FULL_ARTICLE: 'Celý článok',
		REALLY_DELETE: 'Skutočne chcete vymazať tento zdroj?',
		ALL_FEEDS: 'Všetky zdroje',
		PINNED: 'Označené',
		TRASH: 'Kôš',
		MARK_ALL_AS_READ: 'Označiť všetko ako prečítané',
		PROPERTIES: 'Nastavenia',
		UNDELETE: 'Obnoviť',
		NEXT_UNREAD: 'Ďalšia neprečítaná',
		PREV_UNREAD: 'Predošlá neprečítaná',
		MARK_AND_NEXT_UNREAD: 'Prečítať a ďalšia neprečítaná',
		MARK_AND_PREV_UNREAD: 'Prečítať a predošlá neprečítaná',
		PIN: 'O(d)značiť',
		PIN_QUESTION_A: 'Položka "',
		PIN_QUESTION_B: '" je označená. Chcete ju zmazať?',
		MARK_ALL_QUESTION: 'Chcete označiť všetky položky, ako prečítané?',
		ADD_RSS_SOURCE: 'Pridať RSS zdroj',
		UPDATE_ALL: 'Aktualizovať všetko',
		FETCH_TITLE_TIP: 'Ak je toto pole prázdne, tak bude použitý názov zo zdroja.',
		NAME: 'Titulok',
		ADDRESS: 'Adresa',
		JANUARY: 'Január',
		FEBRUARY: 'Február',
		MARCH: 'Marec',
		APRIL: 'Apríl',
		MAY: 'Máj',
		JUNE: 'Jún',
		JULY: 'Júl',
		AUGUST: 'August',
		SEPTEMBER: 'September',
		OCTOBER: 'Október',
		NOVEMBER: 'November',
		DECEMBER: 'December',
		MONDAY: 'Pondelok',
		TUESDAY: 'Utorok',
		WEDNESDAY: 'Streda',
		THURSDAY: 'Štvrtok',
		FRIDAY: 'Piatok',
		SATURDAY: 'Sobota',
		SUNDAY: 'Nedeľa',
		TODAY: 'Dnes',
		YESTERDAY: 'Včera',
		LAST_WEEK: 'Minulý týždeň',
		EARLIER_THIS_MONTH: 'Pred mesiacom',
		MORE: 'Viac',
		SETTINGS: 'Nastavenie',
		EMPTY_TRASH: 'Vysypať kôš',
		RSS_FEED_URL: 'Adresa RSS zdroja: ',
		OPTIONS: 'Ďalšie možnosti',
		UPDATING_FEEDS: 'Aktualizácija zdrojov',

		UNREAD: 'neprečítaných', 
		TOTAL: 'celkom', 
		NEW_FOLDER: 'Nová zložka', 
		DOWNLOAD: 'Stiahnúť', 
		DELETE_ALL_ARTICLES: 'Zmazať všetky správy',
		DELETE_ALL_Q: 'Naozaj chcete zmazať VŠETKY správy?',
		REALLY_EMPTY_TRASH: 'Chcete vymazať všetky spávy z koša?',
		RENAME: 'Premenovať'
	},
	ru: {
		MARK_AS_READ: 'Отметить прочтённой',
		DELETE: 'Удалить',
		UPDATE: 'Обновление',
		PRINT: 'Печать',
		SEARCH: 'Поиск...',
		SEARCH_TIP: 'Поиск новостей. Используйте \':\' чтобы искать в содержимом.',
		NEVER: 'Никогда',
		EVERY_5_MINUTES: 'Каждые 5 минут',
		EVERY_15_MINUTES: 'Каждые 15 минут',
		EVERY_30_MINUTES: 'Каждые 30 минут',
		EVERY_HOUR: 'Каждый час',
		EVERY_2_HOURS: 'Каждые 2 часа',
		EVERY_3_HOURS: 'Каждые 3 часа',
		EVERY_5_HOURS: 'Каждые 5 часов',
		EVERY_10_HOURS: 'Каждые 10 часов',
		EVERY_24_HOURS: 'Каждые 24 часа',
		EVERY_WEEK: 'Каждую неделю',
		USERNAME: 'Логин',
		PASSWORD: 'Пароль',
		CANCEL: 'Отменить',
		OK: 'Применить',
		LAYOUT: 'Внешний вид',
		LINES: 'Строк в названии',
		SORT_ORDER: 'Порядок сортировки',
		DESCENDING: 'По убыванию',
		ASCENDING: 'По возрастанию',
		ONE_LINE: 'Одна',
		TWO_LINES: 'Две',
		AUTO: 'Авто',
		FULL_ARTICLE: 'Полный текст',
		REALLY_DELETE: 'Вы действительно хотите удалить эту рассылку?',
		ALL_FEEDS: 'Все каналы',
		PINNED: 'Закреплённые',
		TRASH: 'Корзина',
		MARK_ALL_AS_READ: 'Отметить всё прочтённым',
		PROPERTIES: 'Свойства',
		UNDELETE: 'Восстановить',
		NEXT_UNREAD: 'Следующая непрочтённая',
		PREV_UNREAD: 'Предыдущая непрочтённая',
		MARK_AND_NEXT_UNREAD: 'Отметить пр. и к следующей',
		MARK_AND_PREV_UNREAD: 'Отметить пр. и к предыдущей',
		PIN: 'Закрепить',
		PIN_QUESTION_A: 'Новость "',
		PIN_QUESTION_B: '" закреплена. Вы действительно хотите её удалить?',
		MARK_ALL_QUESTION: 'Вы действительно хотите отметить все статьи как прочтённые?',
		ADD_RSS_SOURCE: 'Добавить RSS',
		UPDATE_ALL: 'Обновить всё',
		FETCH_TITLE_TIP: 'Если поле пустое, будет использовано название рассылки.',
		NAME: 'Название',
		ADDRESS: 'Адрес',
		JANUARY: 'Январь',
		FEBRUARY: 'Февраль',
		MARCH: 'Март',
		APRIL: 'Апрель',
		MAY: 'Май',
		JUNE: 'Июнь',
		JULY: 'Июль',
		AUGUST: 'Август',
		SEPTEMBER: 'Сентябрь',
		OCTOBER: 'Октябрь',
		NOVEMBER: 'Ноябрь',
		DECEMBER: 'Декабрь',
		MONDAY: 'Понедельник',
		TUESDAY: 'Вторник',
		WEDNESDAY: 'Среда',
		THURSDAY: 'Четверг',
		FRIDAY: 'Пятница',
		SATURDAY: 'Суббота',
		SUNDAY: 'Воскресенье',
		TODAY: 'Сегодня',
		YESTERDAY: 'Вчера',
		LAST_WEEK: 'На прошлой неделе',
		EARLIER_THIS_MONTH: 'В этом месяце',
		MORE: 'Дополнительно',
		SETTINGS: 'Настройки',
		EMPTY_TRASH: 'Очистить корзину',
		RSS_FEED_URL: 'Адрес RSS рассылки:',
		OPTIONS: 'Опции',
		UPDATING_FEEDS: 'Обновление рассылок',

		UNREAD: 'unread',
		TOTAL: 'total',
		NEW_FOLDER: 'New Folder',
		DOWNLOAD: 'Download',
		DELETE_ALL_ARTICLES: 'Delete All Articles',
		DELETE_ALL_Q: 'Do you really want to comletelly delete ALL articles?',
		REALLY_EMPTY_TRASH: 'Do you really want to completly delete all articles from trash?',
		RENAME: 'Rename'
	},
};

