var lang = {
	get c() {
		return this[settings.get('lang')] || this.en;
	},
	en: {
		MARK_AS_READ: 'Mark As (Un)Read',
		DELETE: 'Delete',
		UPDATE: 'Update',
		PRINT: 'Print',
		SEARCH: 'Search for?',
		SEARCH_TIP: 'Search in items. Use \':\' to search in content as well.',
		NEVER: 'Never',
		EVERY_5_MINUTES: 'Every 5 minutes',
		EVERY_15_MINUTES: 'Every 15 minutes',
		EVERY_30_MINUTES: 'Every 30 minutes',
		EVERY_HOUR: 'Every hour',
		EVERY_2_HOURS: 'Every 2 hours',
		EVERY_3_HOURS: 'Every 3 hours',
		EVERY_5_HOURS: 'Every 5 hours',
		EVERY_10_HOURS: 'Every 10 hours',
		EVERY_24_HOURS: 'Every 24 hours',
		EVERY_WEEK: 'Every week',
		USERNAME: 'Username',
		PASSWORD: 'Password',
		CANCEL: 'Cancel',
		OK: 'Ok',
		LAYOUT: 'Layout',
		LINES: 'Lines',
		SORT_ORDER: 'Sort Order',
		DESCENDING: 'Descending',
		ASCENDING: 'Ascending',
		ONE_LINE: 'One-Line',
		TWO_LINES: 'Two-Lines',
		AUTO: 'Auto',
		FULL_ARTICLE: 'Full article',
		REALLY_DELETE: 'Do you really want to delete this feed?',
		ALL_FEEDS: 'All feeds',
		PINNED: 'Pinned',
		TRASH: 'Trash',
		MARK_ALL_AS_READ: 'Mark All As Read',
		PROPERTIES: 'Properties',
		UNDELETE: 'Undelete',
		NEXT_UNREAD: 'Next Unread',
		PREV_UNREAD: 'Previous Unread',
		MARK_AND_NEXT_UNREAD: 'Mark And Next Unread',
		MARK_AND_PREV_UNREAD: 'Mark And Prev Unread',
		PIN: 'Un/Pin',
		PIN_QUESTION_A: 'Item "',
		PIN_QUESTION_B: '" is pinned. Do you really want to delete it?',
		MARK_ALL_QUESTION: 'Do you really want to mark ALL items as read?',
		ADD_RSS_SOURCE: 'Add RSS Source',
		UPDATE_ALL: 'Update all',
		FETCH_TITLE_TIP: 'If empty, it will be fetched.',
		NAME: 'Name',
		ADDRESS: 'Address',
		JANUARY: 'January',
		FEBRUARY: 'February',
		MARCH: 'March',
		APRIL: 'April',
		MAY: 'May',
		JUNY: 'Juny',
		JULY: 'July',
		AUGUST: 'August',
		SEPTEMBER: 'Semptember',
		OCTOBER: 'October',
		NOVEMBER: 'November',
		DECEMBER: 'December',
		MONDAY: 'Monday',
		TUESDAY: 'Tuesday',
		WEDNESDAY: 'Wednesday',
		THURSDAY: 'Thursday',
		FRIDAY: 'Friday',
		SATURDAY: 'Saturday',
		WEDNESDAY: 'Wednesday',
		TODAY: 'Today',
		YESTERDAY: 'Yesterday',
		LAST_WEEK: 'Last Week',
		EARLIER_THIS_MONTH: 'Earlier This Month',
		MORE: 'More',
		SETTINGS: 'Settings'
	},
	cs: {
		MARK_AS_READ: 'Označit jako (Ne)Přečtené',
		DELETE: 'Odstranit',
		UPDATE: 'Načíst',
		PRINT: 'Tisknout',
		SEARCH: 'Co chcete hledat?',
		SEARCH_TIP: 'Prohledávjete položky. Použijte znak \':\' k fulltextovému vyhledávání.',
		NEVER: 'Nikdy',
		EVERY_5_MINUTES: 'Každých 5 minut',
		EVERY_15_MINUTES: 'Každých 15 minut',
		EVERY_30_MINUTES: 'Každých 30 minut',
		EVERY_HOUR: 'Každou hodinu',
		EVERY_2_HOURS: 'Každé 2 hodiny',
		EVERY_3_HOURS: 'Každé 3 hodiny',
		EVERY_5_HOURS: 'Každých 5 hodin',
		EVERY_10_HOURS: 'Každých 10 hodin',
		EVERY_24_HOURS: 'Každých 24 hodin',
		EVERY_WEEK: 'Každý týden',
		USERNAME: 'Jméno',
		PASSWORD: 'Heslo',
		CANCEL: 'Zrušit',
		OK: 'Ok',
		LAYOUT: 'Rozvržení',
		LINES: 'Počet řádek',
		SORT_ORDER: 'Řazení',
		DESCENDING: 'Sestupně',
		ASCENDING: 'Vzestupně',
		ONE_LINE: 'Jeden řádek',
		TWO_LINES: 'Dva řádky',
		AUTO: 'Automaticky',
		FULL_ARTICLE: 'Celý článek',
		REALLY_DELETE: 'Určitě chcete odstranit tento zdroj?',
		ALL_FEEDS: 'Všechny zdroje',
		PINNED: 'Označené',
		TRASH: 'Koš',
		MARK_ALL_AS_READ: 'Označit Vše Za Přečtené',
		PROPERTIES: 'Vlastnosti',
		UNDELETE: 'Obnovit',
		NEXT_UNREAD: 'Další Nepřečtená',
		PREV_UNREAD: 'Předchozí Nepřečtená',
		MARK_AND_NEXT_UNREAD: 'Přečíst A Další Nepřečtená',
		MARK_AND_PREV_UNREAD: 'Přečíst A Předchozí Nepřečtená',
		PIN: 'O(d)značit',
		PIN_QUESTION_A: 'Položka "',
		PIN_QUESTION_B: '" je označena. Určitě ji chcete odstranit?',
		MARK_ALL_QUESTION: 'Určitě chcete označit VŠECHNY položky jako přečtené?',
		ADD_RSS_SOURCE: 'Přidat RSS zdroj',
		UPDATE_ALL: 'Nahrát vše',
		FETCH_TITLE_TIP: 'Pokud je prázdný, bude nahrán ze zdroje.',
		NAME: 'Titulek',
		ADDRESS: 'Adresa',
		JANUARY: 'Leden',
		FEBRUARY: 'Únor',
		MARCH: 'Březen',
		APRIL: 'Duben',
		MAY: 'Květen',
		JUNY: 'Červen',
		JULY: 'Červenec',
		AUGUST: 'Srpen',
		SEPTEMBER: 'Září',
		OCTOBER: 'Říjen',
		NOVEMBER: 'Listopad',
		DECEMBER: 'Prosinec',
		MONDAY: 'Pondělí',
		TUESDAY: 'Úterý',
		WEDNESDAY: 'Středa',
		THURSDAY: 'Čtvrtek',
		FRIDAY: 'Pátek',
		SATURDAY: 'Sobota',
		WEDNESDAY: 'Neděle',
		TODAY: 'Dnes',
		YESTERDAY: 'Včera',
		LAST_WEEK: 'Minulý týden',
		EARLIER_THIS_MONTH: 'Dříve v tomto měsící',
		MORE: 'Více',
		SETTINGS: 'Nastavení'
	},
};